### ISSUE TITLE
Can't "just" push to remote repo

### ISSUE THREAD

**Issue by Friz-zy** [dokku/dokku#1945]
Description of problem:

Can not push into new created app:
```bash
dokku@dokku:~$ dokku apps:create python-getting-started
Creating python-getting-started... done
dokku@dokku:~$ ll python-getting-started/
total 8
drwxrwxr-x 2 dokku dokku 4096 Feb 26 12:17 ./
drwxr-xr-x 9 dokku dokku 4096 Feb 26 12:17 ../

user@host: $ git remote add dokku dokku@dokku.me:python-getting-started
user@host: $ fatal: 'python-getting-started' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I was tried create empty git repo so ssh key works but then dokku does not handle it after pushing:
```bash
dokku@dokku:~/python-getting-started$ git init --bare
Initialized empty Git repository in /home/dokku/python-getting-started/

user@host: $ git push dokku master
Counting objects: 238, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (114/114), done.
Writing objects: 100% (238/238), 37.66 KiB | 0 bytes/s, done.
Total 238 (delta 109), reused 238 (delta 109)
To dokku@dokku.me:python-getting-started
 * [new branch]      master -> master
```

Tried:
1) [issue 116](https://github.com/dokku/dokku/issues/116):
- use `sshcommand acl-add` instead of [Ansible authorized_key](https://docs.ansible.com/ansible/authorized_key_module.html)
- `git push --set-upstream`

2) [`git init --bare`](https://stackoverflow.com/questions/25971580/how-to-set-the-root-application-directory/25971857#25971857)

3) [set hostname `dokku.me`](https://stackoverflow.com/questions/26312714/cannot-push-git-repo-to-dokku-remote-on-digital-ocean-droplet)

Output of the following commands

- `uname -a`:
```
Linux dokku.me 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           993        551        442         10         27        261
-/+ buffers/cache:        262        731
Swap:            0          0          0
```
- `docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
- `docker -D info`:
```
Containers: 33
Images: 50
Storage Driver: devicemapper
 Pool Name: docker-8:1-263133-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.665 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.84 GB
 Metadata Space Used: 4.813 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 993.9 MiB
Name: dokku.me
ID: C6AL:2KPA:FAFB:LGIN:GFNX:ZF7O:DYAP:DWX3:3RI5:JTC6:EOTN:QG4M
Debug mode (server): false
Debug mode (client): true
Fds: 29
Goroutines: 30
System Time: Fri Feb 26 12:34:18 UTC 2016
EventsListeners: 0
Init SHA1: 22082e594df367c79a11672c59a9d5da15851227
Init Path: /usr/lib/docker.io/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```
- `sigil -v`:
```
sigil: command not found
```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v
```
- `dokku version`:
```
0.4.14
```
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
cat: /var/lib/dokku/plugins/available/mariadb/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc21004c0c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7ff06c2edf00, 0x4, 0x4, 0x6aeb58, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/mariadb/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc21004c0c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7feb13e6cf00, 0x4, 0x4, 0x6aeb58, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  mariadb                    enabled    
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
cat: /var/lib/dokku/plugins/available/psql/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc21004c0c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7fb80ee09f00, 0x4, 0x4, 0x6aeb58, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/psql/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100540c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f8b18b5af00, 0x4, 0x4, 0x6aeb58, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  psql                       enabled    
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```
- Link to the exact repository being deployed (if possible/applicable):
`git@github.com:heroku/python-getting-started.git`
- If a deploy is failing:
  - the type of application being deployed (node, php, python, ruby, etc.): python
  - whether or not you have a `Dockerfile` in the root of your repository: No Dockerfile
 
Environment details (AWS, VirtualBox, physical, etc.): Vagrant VirtualBox

How was dokku installed?: `deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main`

**Comment by josegonzalez** [comment]
Can you gist the output of:

```
cat /home/dokku/.ssh/authorized_keys
```

**Comment by Friz-zy** [comment]
you know, you gave me a hint: I use one key for configuration and deployment.
looks like it should be two separate keys. Deployment key should be added with `sshcommand acl-add` or via web interface.

Thank you very mutch, I'll check it soon.

Maybe you should highlight this point in the documentation for the likes of me?

**Comment by josegonzalez** [comment]
It says how to in the deploy tutorial after the first setup [here](http://dokku.viewdocs.io/dokku/application-deployment/).

**Comment by Friz-zy** [comment]
Yes, sorry for the false alarm. I saw note about `sshcommand acl-add` but I didn't think about additional options in autorized_keys and when ansible adds the same key as first line this options cease to work
