### ISSUE TITLE
Errors after upgrading to v0.10.0

### ISSUE THREAD

**Issue by agalisteo** [dokku/dokku#2825]
After upgrading from 0.9.4 to 0.10.0 I get errors when deploy apps or execute dokku commmands.

For example: **dokku apps:list**
```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlExport(0xc82000a2f0, 0x1, 0x1)
	/home/ubuntu/plugn/plugn.go:47 +0x8a0
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc8200b01e0, 0xc82000a2c0, 0x4, 0x4, 0xc820094a00)
	/home/ubuntu/.go_workspace/src/github.com/progrium/go-basher/basher.go:182 +0x2e4
github.com/progrium/go-basher.Application(0xc820094a50, 0xc82004df08, 0x4, 0x4, 0x771b18, 0x7fc86d4e9201)
	/home/ubuntu/.go_workspace/src/github.com/progrium/go-basher/basher.go:64 +0x6d7
main.main()
	/home/ubuntu/plugn/plugn.go:98 +0x5d0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
=====> My Apps
app
```

Output of the following commands
```
uname -a: Linux p4 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
free -m:              total        used        free      shared  buff/cache   available
Mem:           7793        1789        2597          85        3405        5505
Swap:             0           0           0
```
```
docker version:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
docker -D info:


Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 77
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.611GiB
Name: p4
ID: J5ET:BPXV:37RK:QMD5:EV2Y:H2U3:3GQ5:LYMU:5ORK:GB4I:VOGQ:FZVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
You're still missing the output from `dokku report`.

**Comment by josegonzalez** [comment]
I've fixed this in the upcoming 0.10.1 release. We had some extra files from a testing branch that introduced a partial plugin. Upgrading should remove the old plugin, though you'll need to remove the following from your systems:

```shell
rm -rf /var/lib/dokku/plugins/available/network /var/lib/dokku/plugins/enabled/network
```

The above command will not be necessary as of `0.11.0`

**Comment by agalisteo** [comment]
Solved! Thanks @josegonzalez

**Comment by agalisteo** [comment]
Now upgrading to v0.10.1 i get this error:

```
$ apt upgrade
Enabling all core plugins
find: File system loop detected; ‘/var/lib/dokku/plugins/enabled/network/network’ is part of the same file system loop as ‘/var/lib/dokku/plugins/enabled/network’.
find: File system loop detected; ‘/var/lib/dokku/plugins/available/network/network’ is part of the same file system loop as ‘/var/lib/dokku/plugins/available/network’.
find: File system loop detected; ‘/var/lib/dokku/core-plugins/enabled/network/network’ is part of the same file system loop as ‘/var/lib/dokku/core-plugins/enabled/network’.
find: File system loop detected; ‘/var/lib/dokku/core-plugins/available/network/network’ is part of the same file system loop as ‘/var/lib/dokku/core-plugins/available/network’.
dpkg: error processing package dokku (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dokku
```

**Comment by josegonzalez** [comment]
Run the following command to remove the filesystem loops and then upgrade. Silly find...

```
find ${DOKKU_LIB_ROOT}/core-plugins/available -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read -r plugin; do
  rm -f ${DOKKU_LIB_ROOT}/core-plugins/available/$plugin/$plugin
  rm -f ${DOKKU_LIB_ROOT}/core-plugins/enabled/$plugin/$plugin
  rm -f ${DOKKU_LIB_ROOT}/plugins/available/$plugin/$plugin
  rm -f ${DOKKU_LIB_ROOT}/plugins/enabled/$plugin/$plugin
done
```
