### ISSUE TITLE
Rails app won't deploy

### ISSUE THREAD

**Issue by J77J** [dokku/dokku#2884]
Description of problem:

Output of the following commands

[root@server /]# dokku report
-----> uname: Linux server.XXXXX.com 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           1839         712          67          42        1059         882
Swap:          2047          29        2018
-----> docker version: 
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.796GiB
Name: server.XXXXX.com
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.31
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v163
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v109
  heroku-buildpack-java      v52
  heroku-buildpack-gradle    v22
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v69
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.10.3
-----> dokku plugins: 
plugn: 0.3.0
  00_dokku-standard    0.10.3 enabled    dokku core standard plugin
  20_events            0.10.3 enabled    dokku core events logging plugin
  apps                 0.10.3 enabled    dokku core apps plugin
  build-env            0.10.3 enabled    dokku core build-env plugin
  certs                0.10.3 enabled    dokku core certificate management plugin
  checks               0.10.3 enabled    dokku core checks plugin
  common               0.10.3 enabled    dokku core common plugin
  config               0.10.3 enabled    dokku core config plugin
  docker-options       0.10.3 enabled    dokku core docker-options plugin
  domains              0.10.3 enabled    dokku core domains plugin
  enter                0.10.3 enabled    dokku core enter plugin
  git                  0.10.3 enabled    dokku core git plugin
  logs                 0.10.3 enabled    dokku core logs plugin
  named-containers     0.10.3 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.3 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.3 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.10.3 enabled    dokku core proxy plugin
  ps                   0.10.3 enabled    dokku core ps plugin
  repo                 0.10.3 enabled    dokku core repo plugin
  shell                0.10.3 enabled    dokku core shell plugin
  ssh-keys             0.10.3 enabled    dokku core ssh-keys plugin
  storage              0.10.3 enabled    dokku core storage plugin
  tags                 0.10.3 enabled    dokku core tags plugin
  tar                  0.10.3 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
Digital Ocean Droplet

How was Dokku installed?:

I think - following this guide
http://dokku.viewdocs.io/dokku/getting-started/installation/

How reproducible:

Actual Results:

remote: No submodule mapping found in .gitmodules for path 'my_app'
To dokku@myapp.com:my_app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@myapp.com:my_app'

Expected Results:

app to have been deployed without error

I have seen a few answers to the submodule mapping error while googling/stackoverflow etc but I'm not sure I understand the solutions and I'm loathe to start deleting/changing things when I don't understand them. As far as I know I don't have submodules(although I could be wrong), so I don't know where this path has appeared from.

As always any help gratefully received,

Thanks,

Johnny

**Comment by J77J** [comment]
OK - turns out I had another copy of my project inside the project. I have no idea how I managed that - removed it and we're a little further forward - now error is:

```
-----> Cleaning up...
-----> Building fitness_oracle from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
remote: /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
remote: 

remote: gzip: stdin: invalid compressed data--format violated
remote: tar: Unexpected EOF in archive
remote: tar: Unexpected EOF in archive
remote: tar: Error is not recoverable: exiting now
remote:         from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote:         from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:22:in `block in fetch_unpack'
remote:         from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `chdir'
remote:         from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `fetch_unpack'
remote:         from /tmp/buildpacks/01_buildpack-ruby/bin/support/download_ruby:14:in `<main>'
remote: /tmp/tmp.Hzq7YD7nrP/lib/ruby/2.3.0/rubygems.rb:9:in `require': cannot load such file -- rbconfig (LoadError)
remote:         from /tmp/tmp.Hzq7YD7nrP/lib/ruby/2.3.0/rubygems.rb:9:in `<top (required)>'
remote:         from <internal:gem_prelude>:4:in `require'
remote:         from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
To dokku@myapp.com:my_app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@myapp.com:my_app'
```

**Comment by J77J** [comment]
OK - this seems to be a network problem,

tried again a few times and eventually it worked..
