### ISSUE TITLE
Cannot deploy ruby sample app on fresh install

### ISSUE THREAD

**Issue by Floby** [dokku/dokku#2980]
Description of problem:

Following the and the application [deployment guide](http://dokku.viewdocs.io/dokku/deployment/application-deployment/) I get an error when pushing the ruby sample app to the newly created application on dokku.

Output of the following commands

```
$ dokku report
-----> uname: Linux Dokku-host 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total       utilisé      libre     partagé tamp/cache   disponible
Mem:          31862        2713       25511         811        3637       27774
Partition d'échange:       32453           0       32453
-----> docker version: 
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 15
Server Version: 17.10.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-38-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.12GiB
Name: Dokku-host
ID: 7LVV:EY6M:7KLN:2M34:JLX5:ZDSS:TFAA:ZACW:SPJZ:QYTX:ZKPV:BLDS
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
the input device is not a TTY
```

Environment details () : physical ubuntu 16.04

How was Dokku installed? `curl | bash`

How reproducible: every time 

Steps to Reproduce:
1. create app
2. push ruby-sample-app to it

Actual Results:
```
$ git push dokku master
Décompte des objets: 236, fait.
Delta compression using up to 8 threads.
Compression des objets: 100% (135/135), fait.
Écriture des objets: 100% (236/236), 41.85 KiB | 0 bytes/s, fait.
Total 236 (delta 85), reused 236 (delta 85)
-----> Cleaning up...
-----> Building ruby-app from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
remote: /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/shell_helpers.rb:58:in `block in run!': Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 60 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.4.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
remote: 
remote: gzip: stdin: unexpected end of file
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/shell_helpers.rb:52:in `times'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/shell_helpers.rb:52:in `run!'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:22:in `block in fetch_unpack'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `chdir'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `fetch_unpack'
remote: 	from /tmp/buildpacks/01_buildpack-ruby/bin/support/download_ruby:14:in `<main>'
remote: /tmp/buildpacks/01_buildpack-ruby/bin/compile: line 11: /tmp/tmp.uypkPwgMZJ/bin/ruby: No such file or directory
To dokku@dokku.adencf.local:ruby-app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: impossible de pousser des références vers 'dokku@dokku.adencf.local:ruby-app'
```

Expected Results:
+ Deployment successful

**Comment by josegonzalez** [comment]
Are you able to download the file the buildpack is trying to download? If not, that will be the issue.

**Comment by Floby** [comment]
It isn't a local vagrant install, it's a physical box with everything installed from the the [install script](https://raw.githubusercontent.com/dokku/dokku/v0.10.5/bootstrap.sh).

I can download the buildpack from the host, but it turns out that from within the running build container, no host can be resolved, not even google.com, which obviously prevents anything from being downloaded.

Is there a special configuration I have to set up for the company DNS servers (correctly configured through DHCP for the host) to be used from within a running container?

**Comment by Floby** [comment]
After further investigation, the container is using 8.8.8.8 and 8.8.4.4 by default to resolve adresses. Both addresses seem to be blocked by the company network (`dig @8.8.8.8 google.com` just hangs). I'd need the docker containers to use the host's configured DNS servers.

**Comment by Floby** [comment]
So

- By default many images and/or the docker engine setup `8.8.8.8` and `8.8.4.4` as the DNS servers in running containers
- These were blocked by the company network to "encourage" use of their own DNS servers
- I'd have needed those eventually for my apps to run correctly
- [this article](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/) gives a workaround for exactly this use case
- [this closed docker issue](https://github.com/moby/moby/issues/23910) seems to indicate that you can also setup your container to relay DNS requests to the docker host with a little more trickery.
- I used the `/etc/docker/daemon.json` workaround to add my DNS servers in it.
