### ISSUE TITLE
Installation of pyproj

### ISSUE THREAD

**Issue by khamaileon** [dokku/dokku#3290]
I'm trying to migrate my Django app from Heroku to Dokku. All requirement installation went fine except for pyproj. It's look like the installer does not have GCC.
```
Collecting ==1.9.5.1 (from -r requirements.txt (line 88))
  Downloading https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz (4.4MB)
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    unable to execute 'gcc': No such file or directory
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/local/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/lib/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/local/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u1oxwnsj/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/usr/local/lib/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

**Comment by josegonzalez** [comment]
This seems like an issue resulting from our lack of use of buildpack slugs. Because of this, we don't use the `heroku/heroku:16-build` image, meaning we don't have gcc setup.

I don't think we're going to fix this as I don't have the bandwidth to switch how we do app builds, so for the moment you'll need to find a way to add `gcc` to herokuish for builds. This can be done using the `dokku-apt` plugin, available [here](https://github.com/F4-Group/dokku-apt).

**Comment by khamaileon** [comment]
@josegonzalez Thanks for the quick response. I tried dokku-apt without success. I will end up replacing pyproj by an equivalent. Thanks again.
