### ISSUE TITLE
Unable to get Ruby 1.8.7 running

### ISSUE THREAD

**Issue by eliaskg** [dokku/dokku#3398]
## Description of problem

For a legacy project I need to run a Rails 2.x app with Ruby 1.8.7. I thought dokku would be a quick way to get it running. Unfortunately there isn't a build pack for 1.8.7 available anymore.

```
An error occurred while installing ruby-1.8.7

Heroku recommends you use the latest supported Ruby version listed here:
https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

For more information on syntax for declaring a Ruby version see:
https://devcenter.heroku.com/articles/ruby-versions

Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 90 --max-time 600 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-16/ruby-build-1.8.7.tgz -s -o - | tar zxf - ' failed unexpectedly:

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I then found a [legacy Heroku buildpack](https://github.com/attopartners/heroku-buildpack-ruby-1.8.7.) which I set up on the server with `BUILDPACK_URL`

This brought me further but also ended up in an error:

```
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
-----> Ruby/Rails app detected
-----> Using RUBY_VERSION: ruby-1.8.7-p357
-----> 1. vendor/bundle/ruby/1.8
-----> 2. bundler-1.0.21
remote: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/format (LoadError)
remote:   from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote:   from /tmp/build/vendor/bundle/ruby/1.8/gems/bundler-1.0.21/lib/bundler/source.rb:5:in `<top (required)>'
remote:   from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote:   from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote:   from /tmp/build/vendor/bundle/ruby/1.8/gems/bundler-1.0.21/lib/bundler/lockfile_parser.rb:28:in `<class:LockfileParser>'
remote:   from /tmp/build/vendor/bundle/ruby/1.8/gems/bundler-1.0.21/lib/bundler/lockfile_parser.rb:4:in `<module:Bundler>'
remote:   from /tmp/build/vendor/bundle/ruby/1.8/gems/bundler-1.0.21/lib/bundler/lockfile_parser.rb:3:in `<top (required)>'
remote:   from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote:   from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:384:in `lockfile_parser'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:366:in `has_windows_gemfile_lock?'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:233:in `block in build_bundler'
remote:   from /tmp/buildpacks/custom/lib/language_pack/base.rb:81:in `log'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:225:in `build_bundler'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:50:in `block in compile'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:398:in `allow_git'
remote:   from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:48:in `compile'
remote:   from /tmp/buildpacks/custom/lib/language_pack/rails2.rb:38:in `compile'
remote:   from /tmp/buildpacks/custom/bin/compile:8:in `block in <main>'
remote:   from /tmp/buildpacks/custom/lib/language_pack/base.rb:81:in `log'
remote:   from /tmp/buildpacks/custom/bin/compile:7:in `<main>'
```

### How reproducible

Specify in your Gemfile:

`ruby "1.8.7"`

### `dokku report APP_NAME` output

```
-----> uname: Linux localhost 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            996         136         194           6         665         691
       Swap:           255           3         252
-----> docker version: 
       Client:
        Version:           18.09.1
        API version:       1.39
        Go version:        go1.10.6
        Git commit:        4c52b90
        Built:             Wed Jan  9 19:35:59 2019
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          18.09.1
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.6
         Git commit:       4c52b90
         Built:            Wed Jan  9 19:02:44 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 4
        Running: 0
        Paused: 0
        Stopped: 4
       Images: 7
       Server Version: 18.09.1
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
       runc version: 96ec2177ae841256168fcf76954f7177af9446eb
       init version: fec3683
       Security Options:
        seccomp
         Profile: default
       Kernel Version: 4.9.0-8-amd64
       Operating System: Debian GNU/Linux 9 (stretch)
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 996.3MiB
       Name: localhost
       ID: EPZL:FPLW:SHR2:3BXI:IW5T:KGAG:AQ3H:JUIN:C77M:6EIA:LDQJ:4M2I
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine
       
WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.6
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v197
         heroku-buildpack-nodejs    v134
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v146
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v83
         heroku-buildpack-play      v26
         heroku-buildpack-php       v148
         heroku-buildpack-go        v98
         buildpack-nginx            v10
-----> dokku version: 0.13.4
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.13.4 enabled    dokku core standard plugin
         20_events            0.13.4 enabled    dokku core events logging plugin
         apps                 0.13.4 enabled    dokku core apps plugin
         build-env            0.13.4 enabled    dokku core build-env plugin
         certs                0.13.4 enabled    dokku core certificate management plugin
         checks               0.13.4 enabled    dokku core checks plugin
         common               0.13.4 enabled    dokku core common plugin
         config               0.13.4 enabled    dokku core config plugin
         docker-options       0.13.4 enabled    dokku core docker-options plugin
         domains              0.13.4 enabled    dokku core domains plugin
         enter                0.13.4 enabled    dokku core enter plugin
         git                  0.13.4 enabled    dokku core git plugin
         imagemagick          0.1.0 enabled    dokku imagemagick plugin
         logs                 0.13.4 enabled    dokku core logs plugin
         network              0.13.4 enabled    dokku core network plugin
         nginx-vhosts         0.13.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.13.4 enabled    dokku core plugin plugin
         proxy                0.13.4 enabled    dokku core proxy plugin
         ps                   0.13.4 enabled    dokku core ps plugin
         repo                 0.13.4 enabled    dokku core repo plugin
         scheduler-docker-local 0.13.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.13.4 enabled    dokku core shell plugin
         ssh-keys             0.13.4 enabled    dokku core ssh-keys plugin
         storage              0.13.4 enabled    dokku core storage plugin
         tags                 0.13.4 enabled    dokku core tags plugin
         tar                  0.13.4 enabled    dokku core tar plugin

```

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.
