### ISSUE TITLE
Problem with websockets working properly on Docker image.

### ISSUE THREAD

**Issue by m0ngr31** [dokku/dokku#3480]
## Description of problem
Problem with websockets working properly on Docker image.

### How reproducible
100%

### Steps to Reproduce
```bash
dokku apps:create hasura
dokku domains:add hasura "hasura.myapidomain.com"
dokku postgres:create hasura-db
dokku postgres:link hasura-db hasura
dokku config:set hasura HASURA_GRAPHQL_DATABASE_URL="<info from above command>" HASURA_GRAPHQL_ADMIN_SECRET="blahblah" HASURA_GRAPHQL_ENABLE_CONSOLE="true" DOKKU_PROXY_PORT_MAP="http:80:8080"
docker pull hasura/graphql-engine
docker tag hasura/graphql-engine dokku/hasura
dokku tags:deploy hasura
```

#### Actual Results
Then connect with an GraphQL client like Apollo and try to setup a subscription. Hasura will send back an error.

#### Expected Results
The exact same setup deployed on Heroku works.

### `dokku report APP_NAME` output
```bash
-----> uname: Linux dokku-apps 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           2000         701         208          61        1089         978
Swap:             0           0           0
-----> docker version: 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 30
 Running: 9
 Paused: 0
 Stopped: 21
Images: 73
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 171
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-142-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
Total Memory: 1.953GiB
Name: dokku-apps
ID: 4DTW:ZQVP:43RV:HAND:34S5:LUJZ:X3UR:D6NC:WZAZ:4NS3:OAJK:XF3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
: !     Deprecated: Please use plugin:list
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.29
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v159
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v64
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.9.4
-----> dokku plugins: 
plugn: 0.3.0
  00_dokku-standard    0.9.4 enabled    dokku core standard plugin
  20_events            0.9.4 enabled    dokku core events logging plugin
  apps                 0.9.4 enabled    dokku core apps plugin
  build-env            0.9.4 enabled    dokku core build-env plugin
  certs                0.9.4 enabled    dokku core certificate management plugin
  checks               0.9.4 enabled    dokku core checks plugin
  common               0.9.4 enabled    dokku core common plugin
  config               0.9.4 enabled    dokku core config plugin
  docker-options       0.9.4 enabled    dokku core docker-options plugin
  domains              0.9.4 enabled    dokku core domains plugin
  enter                0.9.4 enabled    dokku core enter plugin
  git                  0.9.4 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.9.4 enabled    dokku core logs plugin
  mongo                1.2.7 enabled    dokku mongo service plugin
  named-containers     0.9.4 enabled    dokku core named containers plugin
  nginx-proxy-timeout  0.1.0 enabled    Dokku plugin for setting proxy timeout in nginx config
  nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.9.4 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.9.4 enabled    dokku core proxy plugin
  ps                   0.9.4 enabled    dokku core ps plugin
  repo                 0.9.4 enabled    dokku core repo plugin
  shell                0.9.4 enabled    dokku core shell plugin
  ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
  storage              0.9.4 enabled    dokku core storage plugin
  tags                 0.9.4 enabled    dokku core tags plugin
  tar                  0.9.4 enabled    dokku core tar plugin
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
DigitalOcean

It seems like there is an issue maybe with nginx? I can't seem to figure out exactly why websockets don't quite work properly. It seems to do a handshake, but can't get data.

**Comment by josegonzalez** [comment]
We don't support web sockets by default - pull requests welcome! - so you'll need to configure your nginx.conf.sigil to support web sockets, as documented here: https://www.nginx.com/blog/websocket-nginx/ . Feel free to post in our slack or irc chat if you need help with figuring out the exact configuration.

As an aside, you're running a fairly old version of Dokku and related plugins, and should upgrade :)

**Comment by buhrmi** [comment]
Hey guys, is it still the case that Dokku doesn't support websockets by default? I'm running in the same issue that I can establishe a WebSocket connection to my container, but no frames are actually transferred.

**Comment by paschaldev** [comment]
@buhrmi Please how were you able to establish the connection. My port `6001` is never open

**Comment by josegonzalez** [comment]
I have not tested websocket support, and can make no claims as to whether it will work or not.

**Comment by buhrmi** [comment]
@paschaldev websockets use the same ports as HTTP (80 or 443)....

**Comment by paschaldev** [comment]
@buhrmi Please can you share with me your working configuration `nginx.conf` file that allows websocket. 

I use this PHP Laravel package https://github.com/beyondcode/laravel-websockets.

I've tweaked my configuration so many times but still unable to connect to websocket... When I attempt to test my connection, It's never successful.

```
wsc https://api.[mydomain].com
wsc wss://api.[mydomain].com

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (200)
    at ClientRequest.response (/Users/p/.nvm/versions/node/v12.2.0/lib/node_modules/wsc/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:196:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:572:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:459:22)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
Emitted 'error' event at:
    at ClientRequest.response (/Users/p/.nvm/versions/node/v12.2.0/lib/node_modules/wsc/node_modules/ws/lib/WebSocket.js:721:12)
    at Object.onceWrapper (events.js:284:20)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
```

**Comment by josegonzalez** [comment]
@paschaldev since you opened another issue - #3715 - lets keep all your debugging discussion there. Thanks.
