### ISSUE TITLE
Wrong zero-scaled application build

### ISSUE THREAD

**Issue by divtiply** [dokku/dokku#4398]
## Description of problem
Env vars are not passed to zero-scaled application build

### Steps to Reproduce

```
# dokku ps:scale test web=0 console=0
-----> Scaling test processes: web=0 console=0
# dokku ps:rebuild test
-----> Cleaning up...
-----> Building test from herokuish
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> No change in requirements detected, installing from cache
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
-----> Discovering process types
       Procfile declares types -> console
-----> Releasing test...
-----> Deploying test...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
-----> App Procfile file found
-----> DOKKU_SCALE file exists
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
-----> Running post-deploy
-----> Renaming containers
-----> Checking for postdeploy task
       No postdeploy task found, skipping
output:
=====> Application deployed:
       http://ubuntu-s-1vcpu-1gb-fra1-01
```

#### Actual Results

```
# dokku config:set test FOO=123 BAR=321
-----> Setting config vars
       BAR:  321
       FOO:  123
-----> Restarting app test
 !     App test has not been deployed
```

#### Expected Results

Env vars set, successful app restart/rebuild.

### `dokku report test` output

```
-----> uname: Linux ubuntu-s-1vcpu-1gb-fra1-01 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            981         387         148           0         445         439
       Swap:          2047         667        1380
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.3
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        48d30b5
        Built:             Fri Jan 29 14:33:21 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.3
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       46229ca
         Built:            Fri Jan 29 14:31:32 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.3
         GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc:
         Version:          1.0.0-rc92
         GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
       
       Server:
        Containers: 2
         Running: 2
         Paused: 0
         Stopped: 0
        Images: 15
        Server Version: 20.10.3
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-64-generic
        Operating System: Ubuntu 20.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 981.3MiB
        Name: ubuntu-s-1vcpu-1gb-fra1-01
        ID: PEXX:DINJ:EZKI:6XJI:MN6U:WWU2:K7SU:D2YC:J6JG:HIA2:JF23:ASIT
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.25
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v223
         heroku-buildpack-nodejs    v183
         heroku-buildpack-clojure   v86
         heroku-buildpack-python    v188
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v34
         heroku-buildpack-scala     v88
         heroku-buildpack-play      v26
         heroku-buildpack-php       v189
         heroku-buildpack-go        v151
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.23.2
-----> plugn version: plugn: 0.6.1
-----> dokku plugins: 
         00_dokku-standard    0.23.2 enabled    dokku core standard plugin
         20_events            0.23.2 enabled    dokku core events logging plugin
         app-json             0.23.2 enabled    dokku core app-json plugin
         apps                 0.23.2 enabled    dokku core apps plugin
         builder-cnb          0.23.2 enabled    dokku core builder-cnb plugin
         builder-dockerfile   0.23.2 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.23.2 enabled    dokku core builder-herokuish plugin
         buildpacks           0.23.2 enabled    dokku core buildpacks plugin
         certs                0.23.2 enabled    dokku core certificate management plugin
         checks               0.23.2 enabled    dokku core checks plugin
         common               0.23.2 enabled    dokku core common plugin
         config               0.23.2 enabled    dokku core config plugin
         cron                 0.23.2 enabled    dokku core cron plugin
         docker-options       0.23.2 enabled    dokku core docker-options plugin
         domains              0.23.2 enabled    dokku core domains plugin
         enter                0.23.2 enabled    dokku core enter plugin
         git                  0.23.2 enabled    dokku core git plugin
         logs                 0.23.2 enabled    dokku core logs plugin
         mariadb              1.12.6 enabled    dokku mariadb service plugin
         network              0.23.2 enabled    dokku core network plugin
         nginx-vhosts         0.23.2 enabled    dokku core nginx-vhosts plugin
         plugin               0.23.2 enabled    dokku core plugin plugin
         proxy                0.23.2 enabled    dokku core proxy plugin
         ps                   0.23.2 enabled    dokku core ps plugin
         repo                 0.23.2 enabled    dokku core repo plugin
         resource             0.23.2 enabled    dokku core resource plugin
         scheduler-docker-local 0.23.2 enabled    dokku core scheduler-docker-local plugin
         shell                0.23.2 enabled    dokku core shell plugin
         ssh-keys             0.23.2 enabled    dokku core ssh-keys plugin
         storage              0.23.2 enabled    dokku core storage plugin
         tags                 0.23.2 enabled    dokku core tags plugin
         tar                  0.23.2 enabled    dokku core tar plugin
         trace                0.23.2 enabled    dokku core trace plugin
=====> test app information
       App deploy source:             
       App dir:                       /home/dokku/test
       App locked:                    false
=====> test buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> test ssl information
       Ssl dir:                       /home/dokku/test/tls     
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> test checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> test cron information
       Cron task count:               0
=====> test docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> test domains information
       Domains app enabled:           true                     
       Domains app vhosts:                                     
       Domains global enabled:        true                     
       Domains global vhosts:         ubuntu-s-1vcpu-1gb-fra1-01
=====> test git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       ab51f7a                  
       Git last updated at:           1613079286               
=====> test logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> test network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         
=====> test nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/test-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/test-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:                                  
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
=====> test proxy information
       Proxy enabled:                 true
       Proxy port map:                
       Proxy type:                    nginx
=====> test ps information
       Deployed:                      false
       Processes:                     0
       Ps can scale:                  true
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       false
=====> test resource information
=====> test scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> test storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
At DigitalOcean with `bootstrap.sh`

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect test`
```
# dokku ps:inspect test
"docker container inspect" requires at least 1 argument.
See 'docker container inspect --help'.

Usage:  docker container inspect [OPTIONS] CONTAINER [CONTAINER...]

Display detailed information on one or more containers
Traceback (most recent call last):
  File "/tmp/dokku-1704443-trigger-scheduler-docker-local-scheduler-inspect.CS01Kf", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021/02/11 23:04:05 exit status 1
 !     exit status 1
```
- If a deploy is failing or behaving unexpectedly:
  - Application name: `test`
  - The type of application being deployed (node, php, python, ruby, etc.): *python*
  - If using buildpacks, which custom buildpacks are in use: *herokuish, no custom buildpacks*
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`: `console: python main.py`
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
The problem here is that we check for running containers when doing an is-deployed check. Thats bad. We should instead write out if the thing was deployed in `core-post-deploy`, and then reference that property. If the property does not exist, then we should do a fallback to the container check, writing the response to the property so that the fallback can be skipped in the future.

**Comment by josegonzalez** [comment]
Been working on this, I think the change I want is mostly safe, though need to do some testing.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
