### ISSUE TITLE
Deploying a Django app is stuck on predeploy task, worked fine until recently

### ISSUE THREAD

**Issue by alimony** [dokku/dokku#4606]
## Description of problem

When deploying my Django app, the process is stuck on a predeploy task:

`Executing predeploy task from app.json: /usr/src/app/manage.py migrate --noinput`

Running the same step directly on the machine, e.g. by restarting the app, works fine.

### How reproducible

Happens every time, I've tried the deploy many times, killing the process in between, restarting the app in between, and even restarted the entire machine inbetween.

#### Expected Results

The deploy should pass the redeploy step fine and finish.

### `dokku report test-app` output

```
-----> uname: Linux test-www-01 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            981         535          71          15         374         285
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.6
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        370c289
        Built:             Fri Apr  9 22:47:17 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.6
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       8728dd2
         Built:            Fri Apr  9 22:45:28 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.4
         GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
        runc:
         Version:          1.0.0-rc93
         GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
         scan: Docker Scan (Docker Inc., v0.7.0)
       
       Server:
        Containers: 8
         Running: 6
         Paused: 0
         Stopped: 2
        Images: 28
        Server Version: 20.10.6
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
        runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
        init version: de40ad0
        Security Options:
WARNING: No swap limit support
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-73-generic
        Operating System: Ubuntu 20.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 981.3MiB
        Name: test-www-01
        ID: QV3N:3N3A:SQOF:UPX3:NN6T:2NJM:SGUL:E6X7:XFFX:MXGU:POKU:QL4P
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.27
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v225
         heroku-buildpack-nodejs    v183
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v191
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v190
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.24.7
-----> plugn version: plugn: 0.6.1
-----> dokku plugins: 
         00_dokku-standard    0.24.7 enabled    dokku core standard plugin
         20_events            0.24.7 enabled    dokku core events logging plugin
         app-json             0.24.7 enabled    dokku core app-json plugin
         apps                 0.24.7 enabled    dokku core apps plugin
         builder              0.24.7 enabled    dokku core builder plugin
         builder-dockerfile   0.24.7 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.24.7 enabled    dokku core builder-herokuish plugin
         builder-pack         0.24.7 enabled    dokku core builder-pack plugin
         buildpacks           0.24.7 enabled    dokku core buildpacks plugin
         certs                0.24.7 enabled    dokku core certificate management plugin
         checks               0.24.7 enabled    dokku core checks plugin
         common               0.24.7 enabled    dokku core common plugin
         config               0.24.7 enabled    dokku core config plugin
         cron                 0.24.7 enabled    dokku core cron plugin
         docker-options       0.24.7 enabled    dokku core docker-options plugin
         domains              0.24.7 enabled    dokku core domains plugin
         enter                0.24.7 enabled    dokku core enter plugin
         git                  0.24.7 enabled    dokku core git plugin
         letsencrypt          0.11.7 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.24.7 enabled    dokku core logs plugin
         network              0.24.7 enabled    dokku core network plugin
         nginx-vhosts         0.24.7 enabled    dokku core nginx-vhosts plugin
         plugin               0.24.7 enabled    dokku core plugin plugin
         postgres             1.11.6 enabled    dokku postgres service plugin
         proxy                0.24.7 enabled    dokku core proxy plugin
         ps                   0.24.7 enabled    dokku core ps plugin
         redis                1.13.0 enabled    dokku redis service plugin
         repo                 0.24.7 enabled    dokku core repo plugin
         resource             0.24.7 enabled    dokku core resource plugin
         scheduler-docker-local 0.24.7 enabled    dokku core scheduler-docker-local plugin
         shell                0.24.7 enabled    dokku core shell plugin
         ssh-keys             0.24.7 enabled    dokku core ssh-keys plugin
         storage              0.24.7 enabled    dokku core storage plugin
         tags                 0.24.7 enabled    dokku core tags plugin
         tar                  0.24.7 enabled    dokku core tar plugin
         trace                0.24.7 enabled    dokku core trace plugin
=====> test-app app information
       App deploy source:             
       App dir:                       /home/dokku/test-app
       App locked:                    true
=====> test-app builder information
       Builder computed selected:     
       Builder global selected:       
       Builder selected:              
=====> test-app buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> test-app ssl information
       Ssl dir:                       /home/dokku/test-app/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> test-app checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> test-app cron information
       Cron task count:               0
=====> test-app docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> test-app domains information
       Domains app enabled:           true                     
       Domains app vhosts:                                     
       Domains global enabled:        true                     
       Domains global vhosts:         <redacted>         
=====> test-app git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git last updated at:                                    
=====> test-app logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> test-app network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         
=====> test-app nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/test-app-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/test-app-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:                                  
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> test-app proxy information
       Proxy enabled:                 true
       Proxy port map:                
       Proxy type:                    nginx
=====> test-app ps information
       Deployed:                      false
       Processes:                     0
       Ps can scale:                  true
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       false
=====> test-app resource information
=====> test-app scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> test-app storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts: 
```

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Bootstrap script on DigitalOcean droplet.

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect test-app`

This seems weird to me, running `dokku ps:inspect test-app` I get an error:
```
dokku ps:inspect test-app
"docker container inspect" requires at least 1 argument.
See 'docker container inspect --help'.

Usage:  docker container inspect [OPTIONS] CONTAINER [CONTAINER...]

Display detailed information on one or more containers
Traceback (most recent call last):
  File "/tmp/dokku-159239-trigger-scheduler-docker-local-scheduler-inspect.cyMsYk", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021/05/16 10:41:05 exit status 1
 !     exit status 1
```

**Comment by josegonzalez** [comment]
Can you run your command with a verbose mode? Maybe your migrations are just stalling..

**Comment by alimony** [comment]
I actually ended up destroying and recreating the app, which got it working. I'm sorry I didn't collect more information before doing that.
