### ISSUE TITLE
Failure to set env at runtime

### ISSUE THREAD

**Issue by pedropmedina** [dokku/dokku#4823]
## Description of problem
When deploying the app via ```dokku git:from-image``` dokku fails to set the required ENV variables for the app even thought they are set under the app via ```dokku config:set```. 

### Steps to Reproduce

1. Create new dokku app.
2. Push app to registry
3. Set ENVs via dokku config:set
4. Deploy the app via dokku git:from-image

#### Actual Results

```bash
4e9f2cdf4387: Pulling fs layer
793e63d627b9: Pulling fs layer
bcd7e3c33e7f: Pulling fs layer
fbe7e7dfd913: Pulling fs layer
047456f302af: Pulling fs layer
a37669972f18: Pulling fs layer
0266bcedc82e: Pulling fs layer
03a2bb5e6de6: Pulling fs layer
253f7f6ab8d1: Pulling fs layer
977e22bd8dd0: Pulling fs layer
fbe7e7dfd913: Waiting
047456f302af: Waiting
a37669972f18: Waiting
0266bcedc82e: Waiting
03a2bb5e6de6: Waiting
253f7f6ab8d1: Waiting
977e22bd8dd0: Waiting
4e9f2cdf4387: Verifying Checksum
4e9f2cdf4387: Download complete
bcd7e3c33e7f: Verifying Checksum
bcd7e3c33e7f: Download complete
fbe7e7dfd913: Verifying Checksum
fbe7e7dfd913: Download complete
047456f302af: Verifying Checksum
047456f302af: Download complete
a37669972f18: Verifying Checksum
a37669972f18: Download complete
0266bcedc82e: Verifying Checksum
0266bcedc82e: Download complete
793e63d627b9: Verifying Checksum
793e63d627b9: Download complete
03a2bb5e6de6: Verifying Checksum
03a2bb5e6de6: Download complete
4e9f2cdf4387: Pull complete
977e22bd8dd0: Verifying Checksum
977e22bd8dd0: Download complete
253f7f6ab8d1: Verifying Checksum
253f7f6ab8d1: Download complete
793e63d627b9: Pull complete
bcd7e3c33e7f: Pull complete
fbe7e7dfd913: Pull complete
047456f302af: Pull complete
a37669972f18: Pull complete
0266bcedc82e: Pull complete
03a2bb5e6de6: Pull complete
253f7f6ab8d1: Pull complete
977e22bd8dd0: Pull complete
Digest: sha256:488b0426957f71cda624e22b1a66eec6fd147d2b0731db3e360444fe68355486
Status: Downloaded newer image for ricoma/microservices-netsuite-api@sha256:488b0426957f71cda624e22b1a66eec6fd147d2b0731db3e360444fe68355486
 ---> c0e4b76d720e
Step 2/5 : LABEL com.dokku.docker-image-labeler/alternate-tags=[\"ricoma/microservices-netsuite-api@sha256:488b0426957f71cda624e22b1a66eec6fd147d2b0731db3e360444fe68355486\"]
 ---> Running in c64a4d1bca5c
Removing intermediate container c64a4d1bca5c
 ---> 21bba81773fd
Step 3/5 : LABEL dokku=
 ---> Running in 7fd0c88ca64d
Removing intermediate container 7fd0c88ca64d
 ---> 8ddbc003f991
Step 4/5 : LABEL org.label-schema.schema-version=1.0
 ---> Running in 8094aa8c9926
Removing intermediate container 8094aa8c9926
 ---> f69fcf936350
Step 5/5 : LABEL org.label-schema.vendor=dokku
 ---> Running in dc15a5b33319
Removing intermediate container dc15a5b33319
 ---> 40395953b3ef
Successfully built 40395953b3ef
Successfully tagged dokku/microservices-netsuite-api:latest
-----> Releasing microservices-netsuite-api...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
-----> No Procfile found in app image
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying microservices-netsuite-api...
 !     No procfile found
-----> Attempting pre-flight checks (web.1)
       Waiting for 10 seconds ...
dfff638cb4f230324c91582fa9ff4dd956f22922e5fa145d7b6ad887fd316560
 !     App container failed to start!!
=====> Start of microservices-netsuite-api web container output:
       /app/node_modules/@nestjs/config/dist/config.module.js:61
                       throw new Error(`Config validation error: ${error.message}`);
                       ^
       Error: Config validation error: "TYPEORM_USERNAME" is required. "TYPEORM_PASSWORD" is required
           at Function.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:61:23)
           at Function.forRoot (/app/main.js:10266:39)
           at Object.<anonymous> (/app/main.js:9879:58)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9835:22)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9822:18)
           at __webpack_require__ (/app/main.js:20:30)
           at /app/main.js:84:18
           at Object.<anonymous> (/app/main.js:87:10)
       /app/node_modules/@nestjs/config/dist/config.module.js:61
                       throw new Error(`Config validation error: ${error.message}`);
                       ^
       Error: Config validation error: "TYPEORM_USERNAME" is required. "TYPEORM_PASSWORD" is required
           at Function.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:61:23)
           at Function.forRoot (/app/main.js:10266:39)
           at Object.<anonymous> (/app/main.js:9879:58)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9835:22)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9822:18)
           at __webpack_require__ (/app/main.js:20:30)
           at /app/main.js:84:18
           at Object.<anonymous> (/app/main.js:87:10)
       /app/node_modules/@nestjs/config/dist/config.module.js:61
                       throw new Error(`Config validation error: ${error.message}`);
                       ^
       Error: Config validation error: "TYPEORM_USERNAME" is required. "TYPEORM_PASSWORD" is required
           at Function.forRoot (/app/node_modules/@nestjs/config/dist/config.module.js:61:23)
           at Function.forRoot (/app/main.js:10266:39)
           at Object.<anonymous> (/app/main.js:9879:58)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9835:22)
           at __webpack_require__ (/app/main.js:20:30)
           at Object.<anonymous> (/app/main.js:9822:18)
           at __webpack_require__ (/app/main.js:20:30)
           at /app/main.js:84:18
           at Object.<anonymous> (/app/main.js:87:10)
=====> End of microservices-netsuite-api web container output
```

#### Expected Results
Success deploy with environment variables present at runtime.

<-- Please replace APP_NAME with the name of your app -->

### `dokku report APP_NAME` output

```bash
-----> uname: Linux integ 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            981         347         125           1         507         482
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.13
        API version:       1.40
        Go version:        go1.13.15
        Git commit:        4484c46d9d
        Built:             Wed Sep 16 17:02:52 2020
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.13
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       4484c46d9d
         Built:            Wed Sep 16 17:01:20 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.3.7
         GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
       
       Server:
        Containers: 5
         Running: 1
         Paused: 0
         Stopped: 4
        Images: 8
        Server Version: 19.03.13
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-52-generic
        Operating System: Ubuntu 20.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 981.3MiB
        Name: integ
        ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Username: ricoma
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.30
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v228
         heroku-buildpack-nodejs    v185
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v197
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v196
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.25.4
-----> plugn version: plugn: 0.5.0
-----> dokku plugins: 
         00_dokku-standard    0.25.4 enabled    dokku core standard plugin
         20_events            0.25.4 enabled    dokku core events logging plugin
         app-json             0.25.4 enabled    dokku core app-json plugin
         apps                 0.25.4 enabled    dokku core apps plugin
         builder              0.25.4 enabled    dokku core builder plugin
         builder-dockerfile   0.25.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.25.4 enabled    dokku core builder-herokuish plugin
         builder-null         0.25.4 enabled    dokku core builder-null plugin
         builder-pack         0.25.4 enabled    dokku core builder-pack plugin
         buildpacks           0.25.4 enabled    dokku core buildpacks plugin
         certs                0.25.4 enabled    dokku core certificate management plugin
         checks               0.25.4 enabled    dokku core checks plugin
         common               0.25.4 enabled    dokku core common plugin
         config               0.25.4 enabled    dokku core config plugin
         cron                 0.25.4 enabled    dokku core cron plugin
         docker-options       0.25.4 enabled    dokku core docker-options plugin
         domains              0.25.4 enabled    dokku core domains plugin
         enter                0.25.4 enabled    dokku core enter plugin
         git                  0.25.4 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.25.4 enabled    dokku core logs plugin
         network              0.25.4 enabled    dokku core network plugin
         nginx-vhosts         0.25.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.25.4 enabled    dokku core plugin plugin
         proxy                0.25.4 enabled    dokku core proxy plugin
         ps                   0.25.4 enabled    dokku core ps plugin
         registry             0.25.4 enabled    dokku core registry plugin
         repo                 0.25.4 enabled    dokku core repo plugin
         resource             0.25.4 enabled    dokku core resource plugin
         run                  0.25.4 enabled    dokku core run plugin
         scheduler-docker-local 0.25.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.25.4 enabled    dokku core scheduler-null plugin
         shell                0.25.4 enabled    dokku core shell plugin
         ssh-keys             0.25.4 enabled    dokku core ssh-keys plugin
         storage              0.25.4 enabled    dokku core storage plugin
         tags                 0.25.4 enabled    dokku core tags plugin
         tar                  0.25.4 enabled    dokku core tar plugin
         trace                0.25.4 enabled    dokku core trace plugin
=====> microservices-netsuite-api app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> microservices-netsuite-api app information
       App deploy source:             
       App dir:                       /home/dokku/microservices-netsuite-api
       App locked:                    true
=====> microservices-netsuite-api builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> microservices-netsuite-api builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> microservices-netsuite-api builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> microservices-netsuite-api buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> microservices-netsuite-api ssl information
       Ssl dir:                       /home/dokku/microservices-netsuite-api/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> microservices-netsuite-api checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> microservices-netsuite-api cron information
       Cron task count:               0
=====> microservices-netsuite-api docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> microservices-netsuite-api domains information
       Domains app enabled:           true                     
       Domains app vhosts:                                     
       Domains global enabled:        true                     
       Domains global vhosts:         integ                    
=====> microservices-netsuite-api git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       47d3c87                  
       Git last updated at:           1633105510               
=====> microservices-netsuite-api logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> microservices-netsuite-api network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                
=====> microservices-netsuite-api nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/microservices-netsuite-api-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/microservices-netsuite-api-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:                                  
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> microservices-netsuite-api proxy information
       Proxy enabled:                 true
       Proxy port map:                
       Proxy type:                    nginx
=====> microservices-netsuite-api ps information
       Deployed:                      false
       Processes:                     0
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       false
=====> microservices-netsuite-api registry information
       Registry computed image repo:      dokku/microservices-netsuite-api
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> microservices-netsuite-api resource information
=====> microservices-netsuite-api scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> microservices-netsuite-api storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:  
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?

Installed Dokku via Digital Ocean official droplet. 
NOTE: I updated the dokku version `dokku version 0.25.4` in order to make use of git:from-image feature

**Comment by josegonzalez** [comment]
Seems the issue is that the user was missing spaces when setting their env vars, so a bunch of them were smushed together like:


```
TYPEORM_DATABASE=valueTYPEORM_USERNAME=usernameTYPEORM_PASSWORD=password
```

So the only value that was actually set was `TYPEORM_DATABASE`.
