### ISSUE TITLE
`pack` builder experiences an error on Raspberry Pi `arm64`.

### ISSUE THREAD

**Issue by c4lliope** [dokku/dokku#5214]
### Description of problem

I enabled the `pack` builder on my 64-bit Raspberry Pi OS (`uname -r` -> `5.15.32-v8+`).
On a git push, I see an error.

### dokku report $APP_NAME

```bash
access@raspberrypi:~ $ sudo dokku report check
-----> uname: Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
-----> memory: 
                      total        used        free      shared  buff/cache   available
       Mem:            1849         561         141          90        1147        1150
       Swap:             99          15          84
-----> docker version: 
       Client:
        Version:           20.10.5+dfsg1
        API version:       1.41
        Go version:        go1.15.15
        Git commit:        55c4c88
        Built:             Sat Dec  4 10:53:03 2021
        OS/Arch:           linux/arm64
        Context:           default
        Experimental:      true
       
       Server:
        Engine:
         Version:          20.10.5+dfsg1
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.15.15
         Git commit:       363e9a8
         Built:            Sat Dec  4 10:53:03 2021
         OS/Arch:          linux/arm64
         Experimental:     false
        containerd:
         Version:          1.4.13~ds1
         GitCommit:        1.4.13~ds1-1~deb11u1
        runc:
         Version:          1.0.0~rc93+ds1
         GitCommit:        1.0.0~rc93+ds1-5+b2
        docker-init:
         Version:          0.19.0
         GitCommit:        
-----> docker daemon info: 
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: Support for cgroup v2 is experimental
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         compose: Docker Compose (Docker Inc., v2.6.0)
       
       Server:
        Containers: 0
         Running: 0
         Paused: 0
         Stopped: 0
        Images: 6
        Server Version: 20.10.5+dfsg1
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 1.4.13~ds1-1~deb11u1
        runc version: 1.0.0~rc93+ds1-5+b2
        init version: 
        Security Options:
         seccomp
          Profile: default
         cgroupns
        Kernel Version: 5.15.32-v8+
        Operating System: Debian GNU/Linux 11 (bullseye)
        OSType: linux
        Architecture: aarch64
        CPUs: 4
        Total Memory: 1.806GiB
        Name: raspberrypi
        ID: OR3E:FJ44:HTVQ:GWZ3:B7DX:4CD4:MAVG:B7FG:PXXK:W22C:YSIP:I3MZ
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.30.2
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
 !     herokuish not supported on arm64 architecture
-----> dokku version: dokku version 0.27.5
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.27.5 enabled    dokku core standard plugin
         20_events            0.27.5 enabled    dokku core events logging plugin
         app-json             0.27.5 enabled    dokku core app-json plugin
         apps                 0.27.5 enabled    dokku core apps plugin
         builder              0.27.5 enabled    dokku core builder plugin
         builder-dockerfile   0.27.5 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.5 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.5 enabled    dokku core builder-null plugin
         builder-pack         0.27.5 enabled    dokku core builder-pack plugin
         buildpacks           0.27.5 enabled    dokku core buildpacks plugin
         certs                0.27.5 enabled    dokku core certificate management plugin
         checks               0.27.5 enabled    dokku core checks plugin
         common               0.27.5 enabled    dokku core common plugin
         config               0.27.5 enabled    dokku core config plugin
         cron                 0.27.5 enabled    dokku core cron plugin
         docker-options       0.27.5 enabled    dokku core docker-options plugin
         domains              0.27.5 enabled    dokku core domains plugin
         enter                0.27.5 enabled    dokku core enter plugin
         git                  0.27.5 enabled    dokku core git plugin
         letsencrypt          0.14.2 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.27.5 enabled    dokku core logs plugin
         network              0.27.5 enabled    dokku core network plugin
         nginx-vhosts         0.27.5 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.5 enabled    dokku core plugin plugin
         proxy                0.27.5 enabled    dokku core proxy plugin
         ps                   0.27.5 enabled    dokku core ps plugin
         registry             0.27.5 enabled    dokku core registry plugin
         repo                 0.27.5 enabled    dokku core repo plugin
         resource             0.27.5 enabled    dokku core resource plugin
         run                  0.27.5 enabled    dokku core run plugin
         scheduler            0.27.5 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.5 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.5 enabled    dokku core scheduler-null plugin
         shell                0.27.5 enabled    dokku core shell plugin
         ssh-keys             0.27.5 enabled    dokku core ssh-keys plugin
         storage              0.27.5 enabled    dokku core storage plugin
         trace                0.27.5 enabled    dokku core trace plugin
=====> check app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> check app information
       App created at:                1654910255
       App deploy source:             
       App deploy source metadata:    
       App dir:                       /home/dokku/check
       App locked:                    false
=====> check builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     pack
       Builder global build dir:      
       Builder global selected:       pack
       Builder selected:              
=====> check builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> check builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> check buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> check ssl information
       Ssl dir:                       /home/dokku/check/tls    
       Ssl enabled:                   true                     
       Ssl hostnames:                 check.silicon.am         
       Ssl expires at:                Sep  9 00:02:42 2022 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jun 11 00:02:43 2022 GMT 
       Ssl subject:                   subject=CN = check.silicon.am
       Ssl verified:                  self signed              
=====> check checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> check cron information
       Cron task count:               0
=====> check docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> check domains information
       Domains app enabled:           true                     
       Domains app vhosts:            check.silicon.am         
       Domains global enabled:        true                     
       Domains global vhosts:         silicon.am               
=====> check git information
       Git deploy branch:             main                     
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git last updated at:                                    
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 2: /var/lib/dokku/plugins/available/letsencrypt/command-functions: No such file or directory
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 6: cmd-letsencrypt-report-single: command not found
access@raspberrypi:~ $ 
```

### Additional information

```bash
access@raspberrypi:~ $ sudo dokku ps:inspect check
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo debian
+ DOKKU_DISTRO=debian
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ export DOKKU_CNB_BUILDER=heroku/buildpacks
+ DOKKU_CNB_BUILDER=heroku/buildpacks
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=109189
+ DOKKU_PID=109189
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args ps:inspect check
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=('ps:inspect' 'check')
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ ps:inspect == \-\-\a\p\p ]]
+ [[ ps:inspect =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ check == \-\-\a\p\p ]]
+ [[ check =~ ^--.* ]]
+ next_index=3
+ [[ -z '' ]]
++ echo -e ''
++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+ export DOKKU_GLOBAL_FLAGS=
+ DOKKU_GLOBAL_FLAGS=
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ ps:inspect =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
+ [[ '' == \t\r\u\e ]]
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/2 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ root != \d\o\k\k\u ]]
+ unset TMP TMPDIR TEMP TEMPDIR
+ [[ ! ps:inspect =~ plugin:* ]]
+ [[ ps:inspect != \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ ps:inspect != \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
++ id -un
+ export SSH_USER=root
+ SSH_USER=root
+ sudo -u dokku -E -H /usr/bin/dokku ps:inspect check
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo debian
+ DOKKU_DISTRO=debian
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ export DOKKU_CNB_BUILDER=heroku/buildpacks
+ DOKKU_CNB_BUILDER=heroku/buildpacks
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=109199
+ DOKKU_PID=109199
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args ps:inspect check
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=('ps:inspect' 'check')
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ ps:inspect == \-\-\a\p\p ]]
+ [[ ps:inspect =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ check == \-\-\a\p\p ]]
+ [[ check =~ ^--.* ]]
+ next_index=3
+ [[ -z '' ]]
++ echo -e ''
++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+ export DOKKU_GLOBAL_FLAGS=
+ DOKKU_GLOBAL_FLAGS=
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ ps:inspect =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
+ [[ '' == \t\r\u\e ]]
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/2 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ ps:inspect =~ ^plugin:.* ]]
+ [[ ps:inspect == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ ps:inspect == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
+ [[ -n '' ]]
+ dokku_auth ps:inspect check
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=root
+ SSH_USER=root
+ export SSH_NAME=default
+ SSH_NAME=default
++ wc -l
++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
+ local user_auth_count=1
+ [[ 1 == 0 ]]
+ [[ 1 == 1 ]]
+ [[ -f /var/lib/dokku/plugins/enabled/20_events/user-auth ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd ps:inspect check
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=ps:inspect
+ local PLUGIN_CMD=ps:inspect
+ local implemented=0
+ local script
+ argv=('ps:inspect' 'check')
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/ps
+ [[ /var/lib/dokku/core-plugins/available/ps == *core-plugins* ]]
+ [[ ps:inspect == \p\s\:\i\n\s\p\e\c\t ]]
+ shift 1
+ [[ -n '' ]]
+ set -- ps:inspect check
+ [[ -x /var/lib/dokku/plugins/enabled/ps:inspect/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/ps:inspect/subcommands/ps:inspect ]]
+ [[ -x /var/lib/dokku/plugins/enabled/ps/subcommands/inspect ]]
+ [[ -n inspect ]]
+ /var/lib/dokku/plugins/enabled/ps/subcommands/inspect ps:inspect check
 ?     plugn trigger scheduler-detect [--global]
 ?     plugn trigger scheduler-detect [check]
 ?     plugn trigger scheduler-detect stderr: + source /var/lib/dokku/core-plugins/available/common/functions
 ?     plugn trigger scheduler-detect stderr: ++ set -eo pipefail
 ?     plugn trigger scheduler-detect stderr: ++ [[ -n 1 ]]
 ?     plugn trigger scheduler-detect stderr: ++ set -x
 ?     plugn trigger scheduler-detect stderr: + [[ ! -n '' ]]
 ?     plugn trigger scheduler-detect stderr: 
 ?     plugn trigger scheduler-detect stdout: docker-local
 ?     plugn trigger scheduler-detect stdout: 
 ?     plugn trigger scheduler-detect stderr: + source /var/lib/dokku/core-plugins/available/common/functions
 ?     plugn trigger scheduler-detect stderr: ++ set -eo pipefail
 ?     plugn trigger scheduler-detect stderr: ++ [[ -n 1 ]]
 ?     plugn trigger scheduler-detect stderr: ++ set -x
 ?     plugn trigger scheduler-detect stderr: + [[ ! -n '' ]]
 ?     plugn trigger scheduler-detect stderr: 
 ?     plugn trigger scheduler-detect stdout: docker-local
 ?     plugn trigger scheduler-detect stdout: 
 ?     plugn trigger scheduler-inspect [docker-local check]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/config/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ trigger-scheduler-docker-local-scheduler-inspect docker-local check
+ declare 'desc=scheduler-docker-local scheduler-inspect plugin trigger'
+ declare trigger=scheduler-inspect
+ declare DOKKU_SCHEDULER=docker-local APP=check
+ [[ docker-local != \d\o\c\k\e\r\-\l\o\c\a\l ]]
++ mktemp /tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.XXXXXX
+ local TMP_INSPECT_CMD=/tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.T5OW27
+ trap 'rm -rf '\''/tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.T5OW27'\'' >/dev/null' RETURN INT TERM EXIT
+ cat
++ find /home/dokku/check -maxdepth 1 -name 'CONTAINER.*' -printf '%f\n'
++ sort -t . -k 2 -n
++ xargs
+ local CONTAINER_FILES=
+ CIDS=()
+ local CIDS
+ local PYTHON_BIN=python
+ command -v python3
+ PYTHON_BIN=python3
+ docker container inspect
+ python3 /tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.T5OW27
"docker container inspect" requires at least 1 argument.
See 'docker container inspect --help'.

Usage:  docker container inspect [OPTIONS] CONTAINER [CONTAINER...]

Display detailed information on one or more containers
Traceback (most recent call last):
  File "/tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.T5OW27", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
+ rm -rf /tmp/dokku-109199-trigger-scheduler-docker-local-scheduler-inspect.T5OW27
 !     exit status 1
access@raspberrypi:~ $ 
```

### Output of failing deploy after running: dokku trace:off

```shell
[grace@chesapeake domain]$ g k silicon main
Enumerating objects: 908, done.
Counting objects: 100% (908/908), done.
Delta compression using up to 8 threads
Compressing objects: 100% (498/498), done.
Writing objects: 100% (908/908), 15.04 MiB | 21.18 MiB/s, done.
Total 908 (delta 501), reused 687 (delta 373), pack-reused 0
remote: Resolving deltas: 100% (501/501), done.
-----> Cleaning up...
-----> Building check from cnb stack heroku/buildpacks (experimental)...
latest: Pulling from heroku/buildpacks
Digest: sha256:05554d83007a3535daddcc3e2a4cc9945802a9fce1be2beda95cec838c7070b9
Status: Image is up to date for heroku/buildpacks:latest
20-cnb: Pulling from heroku/heroku
Digest: sha256:e245a61ac1f01b47d66e362f220548e3e8874b7395129adb481ee0f081a265e6
Status: Image is up to date for heroku/heroku:20-cnb
0.14.0: Pulling from buildpacksio/lifecycle
Digest: sha256:3aaef95fe08ab98f9dd2ff90cb85b60336932482a169cdbe197fd7b180e7e308
Status: Image is up to date for buildpacksio/lifecycle:0.14.0
===> ANALYZING
remote: [analyzer] standard_init_linux.go:219: exec user process caused: exec format error
remote: ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 1
remote:  !     Removing invalid image tag dokku/check:latest
remote:  !     App build failed
To silicon.am:check
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'silicon.am:check'
```

### Output of failing deploy after running: dokku trace:on

```shell
Had to crop this; exceedingly long.


+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo debian
+ DOKKU_DISTRO=debian
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ DOKKU_IMAGE=gliderlabs/herokuish:latest-20
+ export DOKKU_CNB_BUILDER=heroku/buildpacks
+ DOKKU_CNB_BUILDER=heroku/buildpacks
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=106322
+ DOKKU_PID=106322
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
...
To silicon.am:check
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'silicon.am:check'
```

**Comment by c4lliope** [comment]
Program code is here: https://base.assembled.app/code/domain

**Comment by josegonzalez** [comment]
You might need to use a different builder for arm... I wonder what the best way to handle this would be.

**Comment by c4lliope** [comment]
@josegonzalez, I had based my `pack` builder decision on https://github.com/dokku/dokku/pull/5201 -
seems like `pack` is being made the builder of choice on arm machines, no?

**Comment by c4lliope** [comment]
```bash
access@raspberrypi:~ $ dpkg --print-architecture 2> /dev/null
arm64
```

**Comment by c4lliope** [comment]
Making do by using `dockerfile` builder - here are some examples.

Ruby + webpack
```
FROM ruby:3.1.0

# Install NodeJS and Yarn
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get install -my gnupg
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get -qqyy install nodejs yarn && rm -rf /var/lib/apt/lists/*

# Add Ruby Gems and node modules
RUN mkdir /program
WORKDIR /program
COPY Gemfile* /program/
COPY package.json /program/
COPY yarn.lock /program/
ENV BUNDLE_PATH /bundle
RUN bundle install --jobs 5 --retry 5 --without development test
RUN yarn install
COPY . /program

ENV RAILS_ENV production
ENV RACK_ENV production
ENV PATH /program/bin:$PATH
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
```

Node
```
FROM node:18-alpine as build
WORKDIR /program
ENV PATH /program/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN yarn --silent
RUN yarn global add react-scripts@5.0.1 --silent
COPY . ./
ENV NODE_OPTIONS --openssl-legacy-provider
RUN yarn run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /program/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
```
