### ISSUE TITLE
Subsequent deploys fail because port 5000 is already used

### ISSUE THREAD

**Issue by w-a-g-y-u** [dokku/dokku#5219]
### Description of problem

The first deploy completes successfully and results in a running app. Subsequent deploys fail because port 5000 is already in use.

```
Pushing to Dokku Host
remote: -----> Cleaning up...        
remote: -----> Building api from herokuish        
remote: -----> Adding BUILD_ENV to build environment...        
remote:        BUILD_ENV added successfully        
remote: -----> Node.js app detected        
remote: 
remote: -----> Creating runtime environment        
remote: 
remote:        NPM_CONFIG_LOGLEVEL=error        
remote:        USE_YARN_CACHE=true        
remote:        NODE_VERBOSE=false        
remote:        NODE_ENV=production        
remote:        NODE_MODULES_CACHE=true        
remote: 
remote: -----> Installing binaries        
remote:        engines.node (package.json):  unspecified        
remote:        engines.npm (package.json):   unspecified (use default)        
remote:        engines.yarn (package.json):  unspecified (use default)        
remote: 
remote:        Resolving node version 16.x...        
remote:        Downloading and installing node 16.15.1...        
remote:        Using default npm version: 8.11.0        
remote:        Resolving yarn version 1.22.x...        
remote:        Downloading and installing yarn (1.22.18)        
remote:        Installed yarn 1.22.18        
remote: 
remote: -----> Restoring cache        
remote:        - yarn cache        
remote: 
remote: -----> Installing dependencies        
remote:        Installing node modules (yarn.lock)        
remote:        yarn install v1.22.18        
remote:        warning package.json: No license field        
remote:        warning backend@1.0.0: No license field        
remote:        [1/4] Resolving packages...        
remote:        [2/4] Fetching packages...        
remote:        [3/4] Linking dependencies...        
remote:        warning " > getstream@7.4.1" has unmet peer dependency "@types/node@>=10".        
remote:        [4/4] Building fresh packages...        
remote:        Done in 7.17s.        
remote: 
remote: -----> Build        
remote: 
remote: -----> Pruning devDependencies        
remote:        yarn install v1.22.18        
remote:        warning package.json: No license field        
remote:        warning backend@1.0.0: No license field        
remote:        [1/4] Resolving packages...        
remote:        [2/4] Fetching packages...        
remote:        [3/4] Linking dependencies...        
remote:        warning " > getstream@7.4.1" has unmet peer dependency "@types/node@>=10".        
remote:        [4/4] Building fresh packages...        
remote:        warning Ignored scripts due to flag.        
remote:        Done in 2.71s.        
remote: 
remote: -----> Caching build        
remote:        - yarn cache        
remote: 
remote: -----> Build succeeded!        
remote:        !     Unmet dependencies don't fail yarn install but may cause runtime issues        
remote:        https://github.com/npm/npm/issu
remote: 
remote: -----> Discovering process types        
remote:        Default types for  -> web        
remote: -----> Releasing api...        
remote: -----> Checking for predeploy task        
remote:        No predeploy task found, skipping        
remote: -----> Checking for release task        
remote:        No release task found, skipping        
remote: -----> App Procfile file found        
remote: =====> Processing deployment checks        
remote:        No CHECKS file found. Simple container checks will be performed.        
remote:        For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples        
remote: -----> Deploying api via the docker-local scheduler...        
remote: -----> Deploying web (count=1)        
remote:        Attempting pre-flight checks (web.1)        
remote:        Waiting for 10 seconds (web.1)        
remote: 1a0944acc873e2d40c5fe81cce314a5d6dde901539468cab1dd88025a5631fde        
remote:  !     App container failed to start (web.1)        
remote: =====> Start of api container output (web.1)        
remote:        > backend@1.0.0 start        
remote:        > node src/server.js        
remote:        Migrating DB if needed        
remote:        Starting app on port 5000        
remote:        node:events:505        
remote:              throw er; // Unhandled 'error' event        
remote:              ^        
remote:        Error: listen EADDRINUSE: address already in use :::5000        
remote:            at Server.setupListenHandle [as _listen2] (node:net:1372:16)        
remote:            at listenInCluster (node:net:1420:12)        
remote:            at Server.listen (node:net:1508:7)        
remote:            at Function.listen (/app/node_modules/express/lib/application.js:618:[24](https://github.com/apa512/backend/runs/6946072716?check_suite_focus=true#step:8:25))        
remote:            at /app/src/server.js:113:7        
remote:            at processTicksAndRejections (node:internal/process/task_queues:96:5)        
remote:        Emitted 'error' event on Server instance at:        
remote:            at emitErrorNT (node:net:1399:8)        
remote:            at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
remote:          code: 'EADDRINUSE',        
remote:          errno: -98,        
remote:          syscall: 'listen',        
remote:          address: '::',        
remote:          port: 5000        
remote:        }        
remote:        > backend@1.0.0 start        
remote:        > node src/server.js        
remote:        Migrating DB if needed        
remote:        Starting app on port 5000        
remote:        node:events:505        
remote:              throw er; // Unhandled 'error' event        
remote:              ^        
remote:        Error: listen EADDRINUSE: address already in use :::5000        
remote:            at Server.setupListenHandle [as _listen2] (node:net:1372:16)        
remote:            at listenInCluster (node:net:1420:12)        
remote:            at Server.listen (node:net:1508:7)        
remote:            at Function.listen (/app/node_modules/express/lib/application.js:618:24)        
remote:            at /app/src/server.js:113:7        
remote:            at processTicksAndRejections (node:internal/process/task_queues:96:5)        
remote:        Emitted 'error' event on Server instance at:        
remote:            at emitErrorNT (node:net:1399:8)        
remote:            at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
remote:          code: 'EADDRINUSE',        
remote:          errno: -98,        
remote:          syscall: 'listen',        
remote:          address: '::',        
remote:          port: 5000        
remote:        }        
remote:        > backend@1.0.0 start        
remote:        > node src/server.js        
remote:        Migrating DB if needed        
remote:        Starting app on port 5000        
remote:        node:events:505        
remote:              throw er; // Unhandled 'error' event        
remote:              ^        
remote:        Error: listen EADDRINUSE: address already in use :::5000        
remote:            at Server.setupListenHandle [as _listen2] (node:net:1372:16)        
remote:            at listenInCluster (node:net:1420:12)        
remote:            at Server.listen (node:net:1508:7)        
remote:            at Function.listen (/app/node_modules/express/lib/application.js:618:24)        
remote:            at /app/src/server.js:113:7        
remote:            at processTicksAndRejections (node:internal/process/task_queues:96:5)        
remote:        Emitted 'error' event on Server instance at:        
remote:            at emitErrorNT (node:net:1399:8)        
remote:            at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
remote:          code: 'EADDRINUSE',        
remote:          errno: -98,        
remote:          syscall: 'listen',        
remote:          address: '::',        
remote:          port: 5000        
remote:        }        
remote:        > backend@1.0.0 start        
remote:        > node src/server.js        
remote:        Migrating DB if needed        
remote:        Starting app on port 5000        
remote:        node:events:505        
remote:              throw er; // Unhandled 'error' event        
remote:              ^        
remote:        Error: listen EADDRINUSE: address already in use :::5000        
remote:            at Server.setupListenHandle [as _listen2] (node:net:1372:16)        
remote:            at listenInCluster (node:net:1420:12)        
remote:            at Server.listen (node:net:1508:7)        
remote:            at Function.listen (/app/node_modules/express/lib/application.js:618:24)        
remote:            at /app/src/server.js:113:7        
remote:            at processTicksAndRejections (node:internal/process/task_queues:96:5)        
remote:        Emitted 'error' event on Server instance at:        
remote:            at emitErrorNT (node:net:1399:8)        
remote:            at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
remote:          code: 'EADDRINUSE',        
remote:          errno: -98,        
remote:          syscall: 'listen',        
remote:          address: '::',        
remote:          port: 5000        
remote:        }        
remote:        > backend@1.0.0 start        
remote:        > node src/server.js        
remote:        Migrating DB if needed        
remote:        Starting app on port 5000        
remote:        node:events:505        
remote:              throw er; // Unhandled 'error' event        
remote:              ^        
remote:        Error: listen EADDRINUSE: address already in use :::5000        
remote:            at Server.setupListenHandle [as _listen2] (node:net:1372:16)        
remote:            at listenInCluster (node:net:1420:12)        
remote:            at Server.listen (node:net:1508:7)        
remote:            at Function.listen (/app/node_modules/express/lib/application.js:618:24)        
remote:            at /app/src/server.js:113:7        
remote:            at processTicksAndRejections (node:internal/process/task_queues:96:5)        
remote:        Emitted 'error' event on Server instance at:        
remote:            at emitErrorNT (node:net:1399:8)        
remote:            at processTicksAndRejections (node:internal/process/task_queues:83:21) {        
remote:          code: 'EADDRINUSE',        
remote:          errno: -98,        
remote:          syscall: 'listen',        
remote:          address: '::',        
remote:          port: 5000        
remote:        }        
remote: =====> End of api container output (web.1)        
remote: parallel: This job failed:        
remote: /var/lib/dokku/plugins/available/scheduler-docker-local/bin/scheduler-deploy-process-container api herokuish dokku/api:latest latest web 1 1        
To ssh://49.12.226.211:22/api
 ! [remote rejected] 6d207130ffb4cbcaac8ec20e[25](https://github.com/apa512/backend/runs/6946072716?check_suite_focus=true#step:8:26)0041b68f734cc1 -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://dokku@49.12.2[26](https://github.com/apa512/backend/runs/6946072716?check_suite_focus=true#step:8:27).[211](https://github.com/apa512/backend/runs/6946072716?check_suite_focus=true#step:8:212):22/api'
```

Because the first deploy succeeds I don't think there's a problem in my app and I have checked that there's not something else running on port 5000.

Does anyone have any idea what's causing this and what to do about it?

### Steps to reproduce

Can't be reproduced because the code is not open sourced. 

### dokku report $APP_NAME

```
-----> uname: Linux apa512 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3835         296        1592          17        1946        3231
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.17
        API version:       1.41
        Go version:        go1.17.11
        Git commit:        100c701
        Built:             Mon Jun  6 23:02:57 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.17
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.11
         Git commit:       a89b842
         Built:            Mon Jun  6 23:01:03 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.6
         GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
        runc:
         Version:          1.1.2
         GitCommit:        v1.1.2-0-ga916309
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         compose: Docker Compose (Docker Inc., v2.6.0)
         scan: Docker Scan (Docker Inc., v0.17.0)
       
       Server:
        Containers: 1
         Running: 1
         Paused: 0
         Stopped: 0
        Images: 16
        Server Version: 20.10.17
        Storage Driver: overlay2
WARNING: No swap limit support
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
        runc version: v1.1.2-0-ga916309
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-120-generic
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.746GiB
        Name: apa512
        ID: 4JBE:SRP7:BLWB:A4WO:L5NA:6R7W:W6G3:JM3L:QMR3:5YBS:KLQG:MIUW
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: 0.5.36
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v240
         heroku-buildpack-nodejs    v196
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v211
         heroku-buildpack-java      v70
         heroku-buildpack-gradle    v36
         heroku-buildpack-scala     v92
         heroku-buildpack-play      v26
         heroku-buildpack-php       v218
         heroku-buildpack-go        v162
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.5
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.27.5 enabled    dokku core standard plugin
         20_events            0.27.5 enabled    dokku core events logging plugin
         app-json             0.27.5 enabled    dokku core app-json plugin
         apps                 0.27.5 enabled    dokku core apps plugin
         builder              0.27.5 enabled    dokku core builder plugin
         builder-dockerfile   0.27.5 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.5 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.5 enabled    dokku core builder-null plugin
         builder-pack         0.27.5 enabled    dokku core builder-pack plugin
         buildpacks           0.27.5 enabled    dokku core buildpacks plugin
         certs                0.27.5 enabled    dokku core certificate management plugin
         checks               0.27.5 enabled    dokku core checks plugin
         common               0.27.5 enabled    dokku core common plugin
         config               0.27.5 enabled    dokku core config plugin
         cron                 0.27.5 enabled    dokku core cron plugin
         docker-options       0.27.5 enabled    dokku core docker-options plugin
         domains              0.27.5 enabled    dokku core domains plugin
         enter                0.27.5 enabled    dokku core enter plugin
         git                  0.27.5 enabled    dokku core git plugin
         letsencrypt          0.15.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.27.5 enabled    dokku core logs plugin
         network              0.27.5 enabled    dokku core network plugin
         nginx-vhosts         0.27.5 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.5 enabled    dokku core plugin plugin
         proxy                0.27.5 enabled    dokku core proxy plugin
         ps                   0.27.5 enabled    dokku core ps plugin
         registry             0.27.5 enabled    dokku core registry plugin
         repo                 0.27.5 enabled    dokku core repo plugin
         resource             0.27.5 enabled    dokku core resource plugin
         run                  0.27.5 enabled    dokku core run plugin
         scheduler            0.27.5 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.5 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.5 enabled    dokku core scheduler-null plugin
         shell                0.27.5 enabled    dokku core shell plugin
         ssh-keys             0.27.5 enabled    dokku core ssh-keys plugin
         storage              0.27.5 enabled    dokku core storage plugin
         trace                0.27.5 enabled    dokku core trace plugin
=====> api app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> api app information
       App created at:                1655530089
       App deploy source:             api
       App deploy source metadata:    api
       App dir:                       /home/dokku/api
       App locked:                    false
=====> api builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> api builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> api builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> api buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> api ssl information
       Ssl dir:                       /home/dokku/api/tls      
       Ssl enabled:                   true                     
       Ssl hostnames:                 api.apa512.com           
       Ssl expires at:                Sep 14 03:49:44 2022 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jun 16 03:49:45 2022 GMT 
       Ssl subject:                   subject=CN = api.apa512.com
       Ssl verified:                  self signed              
=====> api checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> api cron information
       Cron task count:               0
=====> api docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> api domains information
       Domains app enabled:           true                     
       Domains app vhosts:            api.apa512.com          
       Domains global enabled:        true                     
       Domains global vhosts:         apa512.com               
=====> api git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       bde828c                  
       Git last updated at:           1655475114               
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 2: /var/lib/dokku/plugins/available/letsencrypt/command-functions: No such file or directory
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 6: cmd-letsencrypt-report-single: command not found
```

**Comment by josegonzalez** [comment]
Mind updating the `letsencrypt` plugin via `dokku plugin:update letsencrypt`? That should fix the report output.

After that, please re-post the `dokku report $APP` output as well as run `dokku ps:inspect $APP`. Apps run within containers, so unless there is something that is binding the app to host networking, the port shouldn't be reused. The report/ps:inspect output will help me figure this out (hopefully).

**Comment by w-a-g-y-u** [comment]
I am using host networking mode. That's because I need to use an existing PostgreSQL database and I couldn't find a way to connect to it in bridge mode.

**Comment by josegonzalez** [comment]
Ah that definitely explains it (how did you set that btw?).

I'll do a bit of research as there should be a way to reach out to a host service from a container in a more "natural" format without sacrificing this setup. Otherwise you'll need to disable zero downtime deploys and you can't ps:scale that process.

**Comment by w-a-g-y-u** [comment]
```dokku network:set api initial-network host```

I'm running without zero downtime deploys for now.

**Comment by josegonzalez** [comment]
Lots of research [here](https://stackoverflow.com/questions/31249112/allow-docker-container-to-connect-to-a-local-host-postgres-database) but nothing nice unless you're on a mac. Going to continue digging at this though since we should have a definitive answer.

**Comment by josegonzalez** [comment]
Okay I think what you'll want to do is:

- Run `docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'` to get the IP of the `docker0` bridge network. This value will be referenced as `$IP_OF_DOCKER0`
- Ensure postgres can run be connected via `$IP_OF_DOCKER0`
  - Either set your postgres `listen_addresses` option to `*` or `127.0.0.1,$IP_OF_DOCKER0` in `postgresql.conf`.
  - Update `pg_hba.conf` to allow access from either all interfaces or the `$IP_OF_DOCKER0/16`.
  - Restart postgres
- Add a docker-option using `--add-host host.docker.internal:$IP_OF_DOCKER0`. 
- Remove the `initial-network` parameter via `dokku network:set api initial-network`
- Re-enable zero-downtime deploys

All of that is from [this answer](https://stackoverflow.com/a/61722129) on stackoverflow. Similar instructions would be necessary for communicating to other things on the host. Unfortunately, `host.docker.internal` doesn't appear to be something resolvable for anything not using Docker Desktop (so most/all linux hosts), hence the extra work.

This should allow you to deploy with zero-downtime enabled as well as allow you to connect to your host postgres.

Hope the above helps!
