### ISSUE TITLE
How to solve "We're sorry, but something went wrong" ?

### ISSUE THREAD

**Issue by gwendal5** [dokku/dokku#5231]
### Description of problem

Hi I am using the latest version of dokku.
On launch my laravel application give me a blue screen with "we're sorry but something went wrong." 

![image](https://user-images.githubusercontent.com/97025372/175969189-78e6c996-1be3-43f0-a510-8e7e0058d239.png)

This is the building log, everything seems fine 
```bash
gwendal@Radiance:~/Documents/radius$ git push dokku
Énumération des objets: 8, fait.
Décompte des objets: 100% (8/8), fait.
Compression par delta en utilisant jusqu'à 8 fils d'exécution
Compression des objets: 100% (4/4), fait.
Écriture des objets: 100% (5/5), 471 octets | 471.00 Kio/s, fait.
Total 5 (delta 3), réutilisés 0 (delta 0)
-----> Set prod_test to DOKKU_DEPLOY_BRANCH.
-----> Cleaning up...
-----> Building netalis-radius from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs php
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php
=====> Detected Framework: PHP
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote: -----> Installing platform packages...
remote:        - php (8.1.7)
remote:        - apache (2.4.53)
remote:        - composer (2.3.7)
remote:        - librdkafka (1.8.2)
remote:        - nginx (1.20.2)
remote:        - ext-rdkafka (6.0.1)
remote:        NOTICE: detected userland polyfill packages for PHP extensions
remote:        NOTICE: now attempting to install native extension packages
remote:        Installing extensions provided by symfony/polyfill-mbstring:
remote:        - ext-mbstring (bundled with php)
remote:        Installing extensions provided by symfony/polyfill-ctype:
remote:        - ext-ctype (already enabled)
remote: -----> Installing dependencies...
remote:        Composer version 2.3.7 2022-06-06 16:43:28
remote:        Installing dependencies from lock file
remote:        Verifying lock file contents can be installed on current platform.
remote:        Package operations: 74 installs, 0 updates, 0 removals
remote:          - Installing doctrine/inflector (2.0.4): Extracting archive
remote:          - Installing doctrine/lexer (1.2.3): Extracting archive
remote:          - Installing symfony/polyfill-ctype (v1.26.0): Extracting archive
remote:          - Installing webmozart/assert (1.10.0): Extracting archive
remote:          - Installing dragonmantank/cron-expression (v3.3.1): Extracting archive
remote:          - Installing functional-php/fantasy-land (1.0.1): Extracting archive
remote:          - Installing widmogrod/php-functional (6.0.0): Extracting archive
remote:          - Installing guzzlehttp/promises (1.5.1): Extracting archive
remote:          - Installing ralouphie/getallheaders (3.0.3): Extracting archive
remote:          - Installing psr/http-message (1.0.1): Extracting archive
remote:          - Installing psr/http-factory (1.0.1): Extracting archive
remote:          - Installing guzzlehttp/psr7 (2.2.1): Extracting archive
remote:          - Installing symfony/deprecation-contracts (v3.1.0): Extracting archive
remote:          - Installing psr/http-client (1.0.1): Extracting archive
remote:          - Installing guzzlehttp/guzzle (7.4.3): Extracting archive
remote:          - Installing flix-tech/avro-php (4.2.0): Extracting archive
remote:          - Installing symfony/polyfill-mbstring (v1.26.0): Extracting archive
remote:          - Installing beberlei/assert (v3.3.2): Extracting archive
remote:          - Installing flix-tech/confluent-schema-registry-api (7.5.1): Extracting archive
remote:          - Installing flix-tech/avro-serde-php (1.7.1): Extracting archive
remote:          - Installing symfony/http-foundation (v6.1.0): Extracting archive
remote:          - Installing fruitcake/php-cors (v1.2.0): Extracting archive
remote:          - Installing laravel/serializable-closure (v1.2.0): Extracting archive
remote:          - Installing symfony/var-dumper (v6.1.0): Extracting archive
remote:          - Installing symfony/polyfill-intl-normalizer (v1.26.0): Extracting archive
remote:          - Installing symfony/polyfill-intl-grapheme (v1.26.0): Extracting archive
remote:          - Installing symfony/string (v6.1.0): Extracting archive
remote:          - Installing psr/container (2.0.2): Extracting archive
remote:          - Installing symfony/service-contracts (v3.1.0): Extracting archive
remote:          - Installing symfony/console (v6.1.0): Extracting archive
remote:          - Installing nikic/php-parser (v4.14.0): Extracting archive
remote:          - Installing psy/psysh (v0.11.5): Extracting archive
remote:          - Installing voku/portable-ascii (2.0.1): Extracting archive
remote:          - Installing symfony/polyfill-php80 (v1.26.0): Extracting archive
remote:          - Installing phpoption/phpoption (1.8.1): Extracting archive
remote:          - Installing graham-campbell/result-type (v1.0.4): Extracting archive
remote:          - Installing vlucas/phpdotenv (v5.4.1): Extracting archive
remote:          - Installing symfony/css-selector (v6.1.0): Extracting archive
remote:          - Installing tijsverkoyen/css-to-inline-styles (2.2.4): Extracting archive
remote:          - Installing symfony/routing (v6.1.0): Extracting archive
remote:          - Installing symfony/process (v6.1.0): Extracting archive
remote:          - Installing symfony/polyfill-php72 (v1.26.0): Extracting archive
remote:          - Installing symfony/polyfill-intl-idn (v1.26.0): Extracting archive
remote:          - Installing symfony/mime (v6.1.0): Extracting archive
remote:          - Installing psr/event-dispatcher (1.0.0): Extracting archive
remote:          - Installing symfony/event-dispatcher-contracts (v3.1.0): Extracting archive
remote:          - Installing symfony/event-dispatcher (v6.1.0): Extracting archive
remote:          - Installing psr/log (3.0.0): Extracting archive
remote:          - Installing egulias/email-validator (3.2): Extracting archive
remote:          - Installing symfony/mailer (v6.1.0): Extracting archive
remote:          - Installing symfony/error-handler (v6.1.0): Extracting archive
remote:          - Installing symfony/http-kernel (v6.1.0): Extracting archive
remote:          - Installing symfony/finder (v6.1.0): Extracting archive
remote:          - Installing symfony/polyfill-php81 (v1.26.0): Extracting archive
remote:          - Installing ramsey/collection (1.2.2): Extracting archive
remote:          - Installing brick/math (0.9.3): Extracting archive
remote:          - Installing ramsey/uuid (4.3.1): Extracting archive
remote:          - Installing psr/simple-cache (3.0.0): Extracting archive
remote:          - Installing symfony/translation-contracts (v3.1.0): Extracting archive
remote:          - Installing symfony/translation (v6.1.0): Extracting archive
remote:          - Installing nesbot/carbon (2.58.0): Extracting archive
remote:          - Installing monolog/monolog (2.6.0): Extracting archive
remote:          - Installing league/mime-type-detection (1.11.0): Extracting archive
remote:          - Installing league/flysystem (3.0.20): Extracting archive
remote:          - Installing nette/utils (v3.2.7): Extracting archive
remote:          - Installing nette/schema (v1.2.2): Extracting archive
remote:          - Installing dflydev/dot-access-data (v3.0.1): Extracting archive
remote:          - Installing league/config (v1.1.1): Extracting archive
remote:          - Installing league/commonmark (2.3.1): Extracting archive
remote:          - Installing laravel/framework (v9.15.0): Extracting archive
remote:          - Installing laravel/tinker (v2.7.2): Extracting archive
remote:          - Installing mateusjunges/laravel-kafka (v1.7.6): Extracting archive
remote:          - Installing netalisfr/laravel-kafka (dev-master acffc57): Extracting archive
remote:          - Installing php-grape/grape-entity (v1.0.1): Extracting archive
remote:        Generating optimized autoload files
remote:        > Illuminate\Foundation\ComposerScripts::postAutoloadDump
remote:        > @php artisan package:discover --ansi
remote:        Discovered Package: laravel/tinker
remote:        Discovered Package: mateusjunges/laravel-kafka
remote:        Discovered Package: nesbot/carbon
remote:        Discovered Package: netalisfr/laravel-kafka
remote:        Package manifest generated successfully.
remote:        47 packages you are using are looking for funding.
remote:        Use the `composer fund` command to find out more!
remote: -----> Preparing runtime environment...
remote: -----> Checking for additional extensions to install...
       Using release configuration from last framework (PHP).
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing netalis-radius...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
-----> App Procfile file found
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying netalis-radius via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
       Waiting for 10 seconds (web.1)
       Default container check successful (web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
-----> Deploying release (count=0)
-----> Running post-deploy
-----> Associating app with network netalis-kafka_default
-----> App virtual host support disabled, skipping domains setup
-----> Creating http nginx.conf
       Reloading nginx
-----> Renaming containers
       Found previous container(s) (6d59ed5465df) named netalis-radius.web.1
       Renaming container (6d59ed5465df) netalis-radius.web.1 to netalis-radius.web.1.1656339047
       Renaming container netalis-radius.web.1.upcoming-16515 (d5e12404b315) to netalis-radius.web.1
-----> Checking for postdeploy task
       No postdeploy task found, skipping
-----> Updated schedule file
-----> Shutting down old containers in 60 seconds
=====> Application deployed:
       http://10.93.5.15:8000

To 10.93.5.15:netalis-radius
   1155403..e1cf822  prod_test -> prod_test

```

This is the `dokku events` output
```bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

### Steps to reproduce

Deploy a Laravel 9 application on a dokku server

### dokku report $APP_NAME

This is the `dokku report app_name` output

```bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
-----> uname: Linux dokku01.std2.netalis.net 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:          32111        7425        7629         143       17056       24089
       Swap:          8191         103        8088
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.15
        API version:       1.41
        Go version:        go1.17.9
        Git commit:        fd82621
        Built:             Thu May  5 13:19:23 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.15
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.9
         Git commit:       4433bf6
         Built:            Thu May  5 13:17:28 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.4
         GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc:
         Version:          1.1.1
         GitCommit:        v1.1.1-0-g52de29d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         scan: Docker Scan (Docker Inc., v0.17.0)
       
       Server:
        Containers: 53
         Running: 21
         Paused: 0
         Stopped: 32
        Images: 299
        Server Version: 20.10.15
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: active
         NodeID: ioaqcmmwi4fm1ujqi2fvog5zc
         Is Manager: true
         ClusterID: l84uaakmema0q8y71ou6kie26
         Managers: 1
         Nodes: 2
         Default Address Pool: 10.0.0.0/8  
         SubnetSize: 24
         Data Path Port: 4789
         Orchestration:
          Task History Retention Limit: 5
         Raft:
          Snapshot Interval: 10000
          Number of Old Snapshots to Retain: 0
          Heartbeat Tick: 1
          Election Tick: 10
         Dispatcher:
          Heartbeat Period: 5 seconds
         CA Configuration:
          Expiry Duration: 3 months
          Force Rotate: 0
         Autolock Managers: false
         Root Rotation In Progress: false
         Node Address: 10.93.5.15
         Manager Addresses:
          10.93.5.15:2377
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc version: v1.1.1-0-g52de29d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
WARNING: No swap limit support
        Kernel Version: 5.4.0-105-generic
        Operating System: Ubuntu 20.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 12
        Total Memory: 31.36GiB
        Name: dokku01.std2.netalis.net
        ID: PYVI:LSIS:OAGE:5GI6:APDY:FLZS:WELM:AELX:U35W:VKIH:XABX:QRKD
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.8.1build+dce1c9e
-----> herokuish version: 
       herokuish: 0.5.34
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v236
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v205
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v36
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v205
         heroku-buildpack-go        v160
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.0
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
-----> plugn version: plugn: 0.8.2build+1b2e2b4
-----> dokku plugins: 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
         00_dokku-standard    0.27.0 enabled    dokku core standard plugin
         20_events            0.27.0 enabled    dokku core events logging plugin
         app-json             0.27.0 enabled    dokku core app-json plugin
         apps                 0.27.0 enabled    dokku core apps plugin
         builder              0.27.0 enabled    dokku core builder plugin
         builder-dockerfile   0.27.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.0 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.0 enabled    dokku core builder-null plugin
         builder-pack         0.27.0 enabled    dokku core builder-pack plugin
         buildpacks           0.27.0 enabled    dokku core buildpacks plugin
         certs                0.27.0 enabled    dokku core certificate management plugin
         checks               0.27.0 enabled    dokku core checks plugin
         common               0.27.0 enabled    dokku core common plugin
         config               0.27.0 enabled    dokku core config plugin
         cron                 0.27.0 enabled    dokku core cron plugin
         docker-options       0.27.0 enabled    dokku core docker-options plugin
         domains              0.27.0 enabled    dokku core domains plugin
         elasticsearch        1.20.3 enabled    dokku elasticsearch service plugin
         enter                0.27.0 enabled    dokku core enter plugin
         git                  0.27.0 enabled    dokku core git plugin
         letsencrypt          0.14.2 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.27.0 enabled    dokku core logs plugin
         network              0.27.0 enabled    dokku core network plugin
         nginx-vhosts         0.27.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.0 enabled    dokku core plugin plugin
         postgres             1.19.3 enabled    dokku postgres service plugin
         proxy                0.27.0 enabled    dokku core proxy plugin
         ps                   0.27.0 enabled    dokku core ps plugin
         registry             0.27.0 enabled    dokku core registry plugin
         repo                 0.27.0 enabled    dokku core repo plugin
         resource             0.27.0 enabled    dokku core resource plugin
         run                  0.27.0 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.0 enabled    dokku core scheduler-null plugin
         shell                0.27.0 enabled    dokku core shell plugin
         ssh-keys             0.27.0 enabled    dokku core ssh-keys plugin
         storage              0.27.0 enabled    dokku core storage plugin
         trace                0.27.0 enabled    dokku core trace plugin
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> netalis-radius app information
       App created at:                1656341794
       App deploy source:             
       App deploy source metadata:    
       App dir:                       /home/dokku/netalis-radius
       App locked:                    true
=====> netalis-radius builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> netalis-radius buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius ssl information
       Ssl dir:                       /home/dokku/netalis-radius/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> netalis-radius cron information
       Cron task count:               0
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius domains information
       Domains app enabled:           true                     
       Domains app vhosts:                                     
       Domains global enabled:        true                     
       Domains global vhosts:         10.93.5.15               
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
=====> netalis-radius git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git last updated at:                                    
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 2: /var/lib/dokku/plugins/available/letsencrypt/command-functions: No such file or directory
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 6: cmd-letsencrypt-report-single: command not found
2022/06/27 15:04:42 exit status 127
```

### Additional information

The application is using Laravel 9

This is the `dokku ps:inspect app_name` output

```bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
"docker container inspect" requires at least 1 argument.
See 'docker container inspect --help'.

Usage:  docker container inspect [OPTIONS] CONTAINER [CONTAINER...]

Display detailed information on one or more containers
Traceback (most recent call last):
  File "/tmp/dokku-632540-trigger-scheduler-docker-local-scheduler-inspect.nJEn2E", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/tmp/dokku-632540-trigger-scheduler-docker-local-scheduler-inspect.nJEn2E", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/06/27 15:07:02 exit status 1
 !     exit status 1
```

The contents of the Dockerfile : 
```bash
FROM ubuntu:22.04

LABEL maintainer="Taylor Otwell"

ARG WWWGROUP
ARG NODE_VERSION=16
ARG POSTGRES_VERSION=14

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 \
    && mkdir -p ~/.gnupg \
    && chmod 600 ~/.gnupg \
    && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf \
    && echo "keyserver hkp://keyserver.ubuntu.com:80" >> ~/.gnupg/dirmngr.conf \
    && gpg --recv-key 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c \
    && gpg --export 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c > /usr/share/keyrings/ppa_ondrej_php.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
    && apt-get update \
    && apt-get install -y php8.1-cli php8.1-dev \
    php8.1-pgsql php8.1-sqlite3 php8.1-gd \
    php8.1-curl \
    php8.1-imap php8.1-mysql php8.1-mbstring \
    php8.1-xml php8.1-zip php8.1-bcmath php8.1-soap \
    php8.1-intl php8.1-readline \
    php8.1-ldap \
    php8.1-msgpack php8.1-igbinary php8.1-redis php8.1-swoole \
    php8.1-memcached php8.1-pcov php8.1-xdebug \
    && php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && curl -sLS https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarn.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /usr/share/keyrings/pgdg.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y yarn \
    && apt-get install -y mysql-client \
    && apt-get install -y postgresql-client-$POSTGRES_VERSION \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.1

RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail

COPY ./vendor/laravel/sail/runtimes/8.1/start-container /usr/local/bin/start-container
COPY ./vendor/laravel/sail/runtimes/8.1/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./vendor/laravel/sail/runtimes/8.1/php.ini /etc/php/8.1/cli/conf.d/99-sail.ini
RUN chmod +x /usr/local/bin/start-container

# Custom script
RUN apt-get update \
    && apt-get install -y librdkafka-dev
RUN pecl install rdkafka
RUN echo "extension=rdkafka.so" >> /etc/php/8.1/cli/php.ini
# End custom script

EXPOSE 8000

ENTRYPOINT ["start-container"]
```

The content of the Procfile
```bash
web: vendor/bin/heroku-php-apache2 public/
```

**Comment by josegonzalez** [comment]
A few things:

- Do you mind updating your `letsencrypt` plugin via `dokku plugin:update letsencrypt`? A bug for the report output was fixed there. Once you do that, can you update the `dokku report $APP` output in the original post?
- Seems like you say you have a Dockerfile but the app was deployed via herokuish. Seems odd... Did you switch at some point from one to the other? If you switched to herokuish for builds, that may be why the exposed port there says 8000 instead of 5000 (and therefore causing issues). Once I see the updated report output, I can help set that properly.

**Comment by josegonzalez** [comment]
Hmmm I'll take a look (I have a sneaking suspicion it has to do with running it in the `/root` directory).

Can you run the following:

```shell
cd /tmp
sudo dokku plugin:update letsencrypt
```

And then update the report output?

**Comment by gwendal5** [comment]
I updated the dokku report netalis-radius

**Comment by josegonzalez** [comment]
Mind running the following? Seems like letsencrypt still didn't update:

```
cd /tmp
sudo dokku --trace plugin:update letsencrypt
```

Please paste the output of the above command so I can take a look.

**Comment by gwendal5** [comment]
I ran the command and got an exit 0 but the text was so big I cant copy it

**Comment by josegonzalez** [comment]
Can you redirect the output to a file and then [gist](https://gist.github.com/) the file contents?

Regardless, you should be able to run `dokku proxy:ports-clear netalis-radius` and then `dokku ps:rebuild netalis-radius`. I think that should ensure you have the correct ports for your app and can route to it successfully.

**Comment by gwendal5** [comment]
I solved the problem by running these commands
```bash
dokku apps:destroy APP_NAME
dokku apps:create APP_NAME
dokku config:set APP_NAME (all env variables)
(from local dev machine) : git push dokku
dokku proxy:ports-add APP_NAME http:8091:5000
```
