### ISSUE TITLE
App not reachable after dokku update

### ISSUE THREAD

**Issue by akinsteph** [dokku/dokku#5931]
### Description of problem

upgraded dokku to be able to set nginx client-max-body-size
by running `sudo apt-get -qq -y --no-install-recommends install dokku herokuish sshcommand plugn gliderlabs-sigil dokku-update dokku-event-listener`
everything seems fine but app does not come on and linking mariadb ends at
`-----> Running post-deploy
 !     invalid scale output stored by dokku:
 !     Failure while restarting app: exit status 1`
 
 on running `dokku proxy:build-config nest360-wp`
 !     invalid scale output stored by dokku:
 !     exit status 1

### Steps to reproduce

Initial environment: Dokku 0.21.4 on Ubuntu 20.04
have a wp app linked to a mariadb service
upgrade using `sudo apt-get -qq -y --no-install-recommends install dokku herokuish sshcommand plugn gliderlabs-sigil dokku-update dokku-event-listener`

### dokku report $APP_NAME

```
-----> uname: Linux nest360-prod 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           7957         899        5089          48        1968        6725
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           19.03.13
        API version:       1.40
        Go version:        go1.13.15
        Git commit:        4484c46d9d
        Built:             Wed Sep 16 17:02:52 2020
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          19.03.13
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       4484c46d9d
         Built:            Wed Sep 16 17:01:20 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.3.7
         GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info:
       Client:
        Debug Mode: true
        Plugins:
         compose: Docker Compose (Docker Inc., v2.18.1)

       Server:
        Containers: 19
         Running: 17
         Paused: 0
         Stopped: 2
        Images: 72
        Server Version: 19.03.13
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-150-generic
        Operating System: Ubuntu 20.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 7.771GiB
        Name: nest360-prod
        ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.6.0
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v254
         heroku-buildpack-nodejs    v213
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v232
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v234
         heroku-buildpack-go        v174
         heroku-buildpack-nginx     v23
         buildpack-null             v3
-----> dokku version: dokku version 0.30.7
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.7 enabled    dokku core standard plugin
         20_events            0.30.7 enabled    dokku core events logging plugin
         app-json             0.30.7 enabled    dokku core app-json plugin
         apps                 0.30.7 enabled    dokku core apps plugin
         apt                  0.4.1 enabled    Inject deb packages into dokku based on files in project
         builder              0.30.7 enabled    dokku core builder plugin
         builder-dockerfile   0.30.7 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.7 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.7 enabled    dokku core builder-lambda plugin
         builder-null         0.30.7 enabled    dokku core builder-null plugin
         builder-pack         0.30.7 enabled    dokku core builder-pack plugin
         buildpacks           0.30.7 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.7 enabled    dokku core caddy-vhosts plugin
         certs                0.30.7 enabled    dokku core certificate management plugin
         checks               0.30.7 enabled    dokku core checks plugin
         common               0.30.7 enabled    dokku core common plugin
         config               0.30.7 enabled    dokku core config plugin
         cron                 0.30.7 enabled    dokku core cron plugin
         docker-options       0.30.7 enabled    dokku core docker-options plugin
cat: /var/lib/dokku/plugins/available/dokku-dokkuapp/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc0000b8030, 0x2, 0x5fadb9?})
	github.com/dokku/plugn/plugn.go:30 +0x1ab
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc0000cc280, {0xc0000b8000?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc0000dde60, 0x4, 0xc00009e1d0?}, 0x495954?, 0x1, {0xc0000de0c0, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x5fab59?, {0xc0000dde60, 0x4, 0x4}, 0x5caa00?, 0x70?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x40c
cat: /var/lib/dokku/plugins/available/dokku-dokkuapp/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc0000b8030, 0x2, 0x5fadb9?})
	github.com/dokku/plugn/plugn.go:30 +0x1ab
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc0000cc280, {0xc0000b8000?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc0000dde60, 0x4, 0xc00009e1d0?}, 0x495954?, 0x1, {0xc0000de0c0, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x5fab59?, {0xc0000dde60, 0x4, 0x4}, 0x5caa00?, 0x70?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x40c
         dokku-dokkuapp             disabled
         domains              0.30.7 enabled    dokku core domains plugin
         enter                0.30.7 enabled    dokku core enter plugin
         git                  0.30.7 enabled    dokku core git plugin
         haproxy-vhosts       0.30.7 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.13.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.7 enabled    dokku core logs plugin
         mariadb              1.18.0 enabled    dokku mariadb service plugin
         network              0.30.7 enabled    dokku core network plugin
         nginx-max-upload-size 0.1.4 enabled    Set the NGINX maximum upload file size
         nginx-vhosts         0.30.7 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.7 enabled    dokku core plugin plugin
         postgres             1.17.0 enabled    dokku postgres service plugin
         proxy                0.30.7 enabled    dokku core proxy plugin
         ps                   0.30.7 enabled    dokku core ps plugin
         redirect             0.7.1 enabled    Plugin for managing application redirects
         registry             0.30.7 enabled    dokku core registry plugin
         repo                 0.30.7 enabled    dokku core repo plugin
         resource             0.30.7 enabled    dokku core resource plugin
         run                  0.30.7 enabled    dokku core run plugin
         scheduler            0.30.7 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.7 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.7 enabled    dokku core scheduler-null plugin
         shell                0.30.7 enabled    dokku core shell plugin
         ssh-keys             0.30.7 enabled    dokku core ssh-keys plugin
         storage              0.30.7 enabled    dokku core storage plugin
         trace                0.30.7 enabled    dokku core trace plugin
         traefik-vhosts       0.30.7 enabled    dokku core traefik-vhosts plugin
=====> nest360-wp app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> nest360-wp app information
       App created at:                1686792083
       App deploy source:
       App deploy source metadata:
       App dir:                       /home/dokku/nest360-wp
       App locked:                    false
=====> nest360-wp builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> nest360-wp builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> nest360-wp builder-herokuish information
       Builder herokuish computed allowed: true
       Builder herokuish global allowed: true
       Builder herokuish allowed:
=====> nest360-wp builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> nest360-wp builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> nest360-wp buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> nest360-wp caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.7
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> nest360-wp ssl information
       Ssl dir:                       /home/dokku/nest360-wp/tls
       Ssl enabled:                   true
       Ssl hostnames:                 nest360-wp.newborntoolkit.org
       Ssl expires at:                Sep  6 14:52:32 2023 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jun  8 14:52:33 2023 GMT
       Ssl subject:                   subject=CN = nest360-wp.newborntoolkit.org
       Ssl verified:                  self signed
=====> nest360-wp checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> nest360-wp cron information
       Cron task count:               0
=====> nest360-wp docker options information
       Docker options build:          --link dokku.mariadb.nest360_wp_prod:dokku-mariadb-nest360-wp-prod
       Docker options deploy:         --link dokku.mariadb.nest360_wp_prod:dokku-mariadb-nest360-wp-prod --restart=on-failure:10 -v /var/lib/dokku/data/storage/nest360-wp/languages:/app/wp-content/languages -v /var/lib/dokku/data/storage/nest360-wp/plugins:/app/wp-content/plugins -v /var/lib/dokku/data/storage/nest360-wp/uploads:/app/wp-content/uploads
       Docker options run:            --link dokku.mariadb.nest360_wp_prod:dokku-mariadb-nest360-wp-prod -v /var/lib/dokku/data/storage/nest360-wp/languages:/app/wp-content/languages -v /var/lib/dokku/data/storage/nest360-wp/plugins:/app/wp-content/plugins -v /var/lib/dokku/data/storage/nest360-wp/uploads:/app/wp-content/uploads
=====> nest360-wp domains information
       Domains app enabled:           true
       Domains app vhosts:            nest360-wp.newborntoolkit.org
       Domains global enabled:        true
       Domains global vhosts:         newborntoolkit.org www.newborntoolkit.org
=====> nest360-wp git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       cee2f992
       Git source image:
       Git last updated at:           1686301756
=====> nest360-wp haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> nest360-wp logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> nest360-wp network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.8:5000
=====> nest360-wp nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/nest360-wp-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:    100M
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/nest360-wp-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1686792234
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> nest360-wp proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> nest360-wp ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 54083cb415c)
=====> nest360-wp registry information
       Registry computed image repo:      dokku/nest360-wp
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> nest360-wp resource information
=====> nest360-wp scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> nest360-wp scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> nest360-wp storage information
       Storage build mounts:
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/nest360-wp/languages:/app/wp-content/languages -v /var/lib/dokku/data/storage/nest360-wp/plugins:/app/wp-content/plugins -v /var/lib/dokku/data/storage/nest360-wp/uploads:/app/wp-content/uploads
       Storage run mounts:            -v /var/lib/dokku/data/storage/nest360-wp/languages:/app/wp-content/languages -v /var/lib/dokku/data/storage/nest360-wp/plugins:/app/wp-content/plugins -v /var/lib/dokku/data/storage/nest360-wp/uploads:/app/wp-content/uploads
=====> nest360-wp traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:v2.8
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik priority:
```

### Additional information

Container Inspect Output 
```
[
    {
        "AppArmorProfile": "docker-default",
        "Args": [
            "web"
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/start",
                "web"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "PORT=5000",
                "USER=herokuishuser",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=XXXXXX"
            ],
            "Hostname": "54083cb415cc",
            "Image": "dokku/nest360-wp:latest",
            "Labels": {
                "com.dokku.app-name": "nest360-wp",
                "com.dokku.container-type": "deploy",
                "com.dokku.dyno": "web.1",
                "com.dokku.image-stage": "release",
                "com.dokku.process-type": "web",
                "dokku": "",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "",
            "Volumes": null,
            "WorkingDir": ""
        },
        "Created": "2023-06-09T09:08:43.730115939Z",
        "Driver": "overlay2",
        "ExecIDs": null,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ae047a72e0b6df546194a247251b2ae8db563dc92e673da145f2f55278af1f18-init/diff:/var/lib/docker/overlay2/fd631a7f56f1047ef59b15f5a62f8f25502f00bcaeec352ea757b600d5c789f1/diff:/var/lib/docker/overlay2/d3f61a62608a9da10a827557eca9b4d6a129732c38a083dcd9afbdee2038355d/diff:/var/lib/docker/overlay2/ad89751d949dfbc2f6c2c875522531557793141b9353fe01a83317a9b5f302af/diff:/var/lib/docker/overlay2/7a750d7e370b441e1f9a767929d7e1443d309c905531db3b2248444a62e967e3/diff:/var/lib/docker/overlay2/cb8bcb78378148615232e2b0732011eec9b98e29a3424534970da42f6aefa5fc/diff:/var/lib/docker/overlay2/5614c8127fa02aacd761e1efe48c8f6df2fe6e002b747003c18447892df36825/diff:/var/lib/docker/overlay2/31b3536a78bdadc46cb88a3c50e0f6cf94fb7119eae9d2f31fc0e25c443872a7/diff:/var/lib/docker/overlay2/4efe79f3c127183fd96a6f188e68a40ac54d01655695ca6e7690b86847054bbc/diff:/var/lib/docker/overlay2/72811bb9c28dc15f741cfb8488877851d460cdbec376ad0f81eac6bfaf24363a/diff:/var/lib/docker/overlay2/d630dca098d5f22ffd6da90801c3054aa79805048c6b2dd47cd5acf48dc289a9/diff:/var/lib/docker/overlay2/ca4740f9464caede5d2a59688230f9709af2a9e63e5b81cdb2bc661230e93767/diff:/var/lib/docker/overlay2/40a71248114edfe0a803fa1cda3ff4da906acfab82d6b32901004fcb068360e4/diff:/var/lib/docker/overlay2/1d0613ea75384886e3b6b884a2eb61746b31d63d1ec040f6bdcced489563c0f0/diff:/var/lib/docker/overlay2/bf0fdaf11d50bdb1381a9b932e6d1fa7456372d02d4a1ece020342f46ce53b82/diff:/var/lib/docker/overlay2/f4ef365a7df50734d1a078a220b8f8731eab0e5f3144bb85cbb8f27f31728fa3/diff:/var/lib/docker/overlay2/1446232250fcb3100c41169ed84eec17b9974c4d6560152d60c928302afc08c9/diff:/var/lib/docker/overlay2/4784066a41fe0a68828dae2130b3a6837beea10d6dacce5cf67234f5502591a7/diff:/var/lib/docker/overlay2/1bf868816b5528c4ab961cecda728b9c34fc3c2bcddef90f43e3ad2bd56f80ae/diff:/var/lib/docker/overlay2/ca47f04e993f4676bde48e6cd3fe8062e1111b4cbcfc6f9c5479f4114d9c4ca4/diff",
                "MergedDir": "/var/lib/docker/overlay2/ae047a72e0b6df546194a247251b2ae8db563dc92e673da145f2f55278af1f18/merged",
                "UpperDir": "/var/lib/docker/overlay2/ae047a72e0b6df546194a247251b2ae8db563dc92e673da145f2f55278af1f18/diff",
                "WorkDir": "/var/lib/docker/overlay2/ae047a72e0b6df546194a247251b2ae8db563dc92e673da145f2f55278af1f18/work"
            },
            "Name": "overlay2"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": [
                "/var/lib/dokku/data/storage/nest360-wp/uploads:/app/wp-content/uploads",
                "/var/lib/dokku/data/storage/nest360-wp/languages:/app/wp-content/languages",
                "/var/lib/dokku/data/storage/nest360-wp/plugins:/app/wp-content/plugins"
            ],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceWriteIOps": null,
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Cgroup": "",
            "CgroupParent": "",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "Devices": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "Init": true,
            "IpcMode": "private",
            "Isolation": "",
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "Links": [
                "/dokku.mariadb.nest360_wp_prod:/nest360-wp.web.1/dokku-mariadb-nest360-wp-prod"
            ],
            "LogConfig": {
                "Config": {},
                "Type": "json-file"
            },
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "NanoCpus": 0,
            "NetworkMode": "default",
            "OomKillDisable": false,
            "OomScoreAdj": 0,
            "PidMode": "",
            "PidsLimit": null,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 10,
                "Name": "on-failure"
            },
            "Runtime": "runc",
            "SecurityOpt": null,
            "ShmSize": 67108864,
            "UTSMode": "",
            "Ulimits": null,
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/var/lib/docker/containers/54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa/hostname",
        "HostsPath": "/var/lib/docker/containers/54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa/hosts",
        "Id": "54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa",
        "Image": "sha256:63417497f9034fbedc79b8dc745556dbf92982c860dffc70955b4d3b5d4b2ce1",
        "LogPath": "/var/lib/docker/containers/54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa/54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa-json.log",
        "MountLabel": "",
        "Mounts": [
            {
                "Destination": "/app/wp-content/plugins",
                "Mode": "",
                "Propagation": "rprivate",
                "RW": true,
                "Source": "/var/lib/dokku/data/storage/nest360-wp/plugins",
                "Type": "bind"
            },
            {
                "Destination": "/app/wp-content/uploads",
                "Mode": "",
                "Propagation": "rprivate",
                "RW": true,
                "Source": "/var/lib/dokku/data/storage/nest360-wp/uploads",
                "Type": "bind"
            },
            {
                "Destination": "/app/wp-content/languages",
                "Mode": "",
                "Propagation": "rprivate",
                "RW": true,
                "Source": "/var/lib/dokku/data/storage/nest360-wp/languages",
                "Type": "bind"
            }
        ],
        "Name": "/nest360-wp.web.1",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "3d9b0ac96f329634a797e44646642d5ee50cd714bea7eef5883a2bb66c57611f",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "172.17.0.9",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "02:42:ac:11:00:09",
            "Networks": {
                "bridge": {
                    "Aliases": null,
                    "DriverOpts": null,
                    "EndpointID": "3d9b0ac96f329634a797e44646642d5ee50cd714bea7eef5883a2bb66c57611f",
                    "Gateway": "172.17.0.1",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.9",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "Links": null,
                    "MacAddress": "02:42:ac:11:00:09",
                    "NetworkID": "4756bc54eedee914ee8c26e5eac05e48dd7edafdcc9ad70976907684bc2066ad"
                }
            },
            "Ports": {},
            "SandboxID": "c803d4c8be216fb8df6a2e69dc956f56898193de231715a3033edec6473fa088",
            "SandboxKey": "/var/run/docker/netns/c803d4c8be21",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null
        },
        "Path": "/start",
        "Platform": "linux",
        "ProcessLabel": "",
        "ResolvConfPath": "/var/lib/docker/containers/54083cb415cc9faeaf03d1a451edfe309e69010239559dea62e78c74bad717fa/resolv.conf",
        "RestartCount": 0,
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "2023-06-15T01:37:40.04334305Z",
            "OOMKilled": false,
            "Paused": false,
            "Pid": 1618,
            "Restarting": false,
            "Running": true,
            "StartedAt": "2023-06-15T01:38:12.254610387Z",
            "Status": "running"
        }
    }
]
```
The nginx configuration 
` !     No nginx.conf exists for nest360-wp` (which is weird, because the nginx.conf file and nginx.conf.d folder exist)

**Comment by josegonzalez** [comment]
You'll need to run ps:scale to get the correct scale counts for your app.

**Comment by akinsteph** [comment]
> You'll need to run ps:scale to get the correct scale counts for your app.

I did run ps:scale and nothing was set
Set it to web=1

**Comment by josegonzalez** [comment]
Known bug I'm working on, can you make sure the caddy/traefik/haproxy proxy services are stopped?

**Comment by akinsteph** [comment]
> Known bug I'm working on, can you make sure the caddy/traefik/haproxy proxy services are stopped?

this has been done

**Comment by josegonzalez** [comment]
What's the output of nginx -t? Also, I might be able to help faster via slack/.discord

**Comment by akinsteph** [comment]
> What's the output of nginx -t? Also, I might be able to help faster via slack/.discord

nginx -t  outputs
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by josegonzalez** [comment]
Okay do you mind deploying or rebuilding one app at a time? And posting the errors/stopping as you do so we can fix them?

**Comment by josegonzalez** [comment]
Also I should bring back that migration code for scaling, this has been a terrible user experience :(

**Comment by akinsteph** [comment]
> Okay do you mind deploying or rebuilding one app at a time? And posting the errors/stopping as you do so we can fix them?
the first try
```
root@nest360-prod:/home/dokku/nest360-api# dokku ps:scale nest360-wp web=1
-----> Scaling nest360-wp processes: web=1
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
       Waiting for 10 seconds (web.1)
       Default container check successful (web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
=====> Triggering early nginx proxy rebuild
-----> Ensuring network configuration is in sync for nest360-wp
-----> Configuring nest360-wp.newborntoolkit.org...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS
-----> Setting max upload size to 2M
/var/lib/dokku/plugins/enabled/redirect/nginx-pre-reload: line 7: /var/lib/dokku/plugins/available/proxy/functions: No such file or directory
 !     exit status 1
```

**Comment by akinsteph** [comment]
> Also I should bring back that migration code for scaling, this has been a terrible user experience :(

migration code for scaling?
terrible user experience, I agree

**Comment by josegonzalez** [comment]
Update your redirect plugin to fix that issue.

**Comment by akinsteph** [comment]
> Update your redirect plugin to fix that issue.

Done thanks works fine 
```
-----> Scaling nest360-wp processes: web=1
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
       Waiting for 10 seconds (web.1)
       Default container check successful (web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
=====> Triggering early nginx proxy rebuild
-----> Ensuring network configuration is in sync for nest360-wp
-----> Configuring nest360-wp.newborntoolkit.org...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS
-----> Setting max upload size to 2M
       Reloading nginx
-----> Running post-deploy
-----> Ensuring network configuration is in sync for nest360-wp
-----> Configuring nest360-wp.newborntoolkit.org...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS
-----> Setting max upload size to 2M
       Reloading nginx
-----> Renaming containers
       Renaming container nest360-wp.web.1.upcoming-23111 (95c8144f6c1e) to nest360-wp.web.1
-----> Checking for postdeploy task
       No postdeploy task found, skipping
-----> Updated schedule file
-----> Shutting down old containers in 60 seconds
```
How about changing the value the max upload size is been set to

**Comment by josegonzalez** [comment]
You can change that like so: https://dokku.com/docs/networking/proxies/nginx/#specifying-a-custom-client_max_body_size

**Comment by LukasSkywalker** [comment]
> tried using the `dokku nginx:set APP_NAME client-body-max-size value` but it breaks nginx with '"client_max_body_size" directive is duplicate in /home/dokku/nAPP_NAME/nginx.conf.d/upload.conf' error

@josegonzalez The following might be caused by a plugin i once wrote: https://github.com/Zeilenwerk/dokku-nginx-max-upload-size
I will try to get the owners to deprecate it. If it is installed and enabled while people upgrade to Dokku 0.23+, the `client_max_body_size` directive is duplicated.

**Comment by josegonzalez** [comment]
Already posted here: https://github.com/Zeilenwerk/dokku-nginx-max-upload-size/issues/3
