### ISSUE TITLE
On push, cannot read environment variables set on system, or in app-wide plugin, or app-specifically, within a plugin context

### ISSUE THREAD

**Issue by zachfeldman** [dokku/dokku#6089]
### Description of problem

I've been developing a plugin, https://github.com/zachfeldman/dokku-cf-tunnel-update, to expose Dokku apps on a home server via Cloudflare tunnels by keeping their service IPs updated on app deployments and restarts.

This is working great when I'm logged into my server and restart the app, whether I'm my user or the `dokku` user. It is also working with `systemd` on system restart. Unfortunately, it's not working when I push my apps in the context of git push/buildpacks.

Output of a push where I try to echo out the env var (truncated). Relevant line is "Debug account UUID" where I try to echo out this env var and it is blank:
```
zach@zach-laptopw:~/dev/dialacompliment23 (main)$ git push dokku main -f
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 20 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 429 bytes | 429.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
-----> Cleaning up...
-----> Building dialacompliment from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Ruby app detected
-----> Installing bundler 2.3.25
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-3.1.3
-----> Installing dependencies using bundler 2.3.25
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Using rake 13.0.6
    <truncated>
       Using twilio-ruby 3.11.0
       Bundle complete! 22 Gemfile dependencies, 69 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Bundle completed (0.19s)
       Cleaning up the bundler cache.
       Removing bundler (2.3.25)
-----> Installing node-v16.18.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Asset precompilation completed (0.65s)
       Cleaning assets
       Running: rake assets:clean
-----> Detecting rails configuration
<truncated>
-----> Discovering process types
       Default types for  -> console, web, rake
-----> Releasing dialacompliment...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying dialacompliment via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
       Waiting for 10 seconds (web.1)
       Default container check successful (web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
=====> Triggering early nginx proxy rebuild
-----> Ensuring network configuration is in sync for dialacompliment
-----> Configuring dialacompliment.com...(using built-in template)
-----> Creating http nginx.conf
       Reloading nginx
-----> Running post-deploy
remote:  !     Detected IPv4 domain name with nginx proxy enabled.
remote:  !     Ensure the default nginx site is removed before continuing.
-----> Ensuring network configuration is in sync for dialacompliment
-----> Configuring dialacompliment.com...(using built-in template)
-----> Creating http nginx.conf
       Reloading nginx
-----> Renaming containers
       Found previous container(s) (c68a5f6d3cd7) named dialacompliment.web.1
       Renaming container (c68a5f6d3cd7) dialacompliment.web.1 to dialacompliment.web.1.1690994266
       Renaming container dialacompliment.web.1.upcoming-13673 (84aa820bfe2a) to dialacompliment.web.1
-----> Checking for postdeploy task
       No postdeploy task found, skipping
Sourcing /home/dokku/.bashrc for credentials
Debug account UUID

debug whoami
dokku
debug pwd
/tmp/dokku-230686-git_build_app_repo.IUyLHK
Running dokku-cf-tunnel-update Ruby script
Reading /home/dokku/.cf-tunnel-config file, if it exists, or using default
Updating ingress list with current apps
remote: cat: /home/dokku/snap/nginx.conf: No such file or directory
{"hostname"=>"dialacompliment.com", "service"=>"http://172.17.0.7:5000"}
{"hostname"=>"djmuzach.com", "service"=>"http://172.17.0.8:5000"}
{"service"=>"http_status:404"}
Cloudflare API Response code: 404
Cloudflare API Response body: {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/accounts/cfd_tunnel/configurations, perhaps your object identifier is invalid?"}],"messages":[]}
-----> Shutting down old containers in 60 seconds
=====> Application deployed:
       http://dialacompliment.com

To ssh.exa.zone:dialacompliment
 + dfcc157...1b0af62 main -> main (forced update)
```

### Steps to reproduce

- Install the plugin following the README https://github.com/zachfeldman/dokku-cf-tunnel-update, including Cloudflare configuration
- Try pushing an app
- We try to echo out the Cloudflare UUID, but it doesn't show, and the API request to Cloudflare fails

### dokku report $APP_NAME

```
penguin@penguin-server:~$ dokku report djmuzach
[sudo] password for penguin: 
-----> uname: Linux penguin-server 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                      total        used        free      shared  buff/cache   available
       Mem:           31877        1163       27020          40        3693       30215
       Swap:           2047           0        2047
-----> docker version: 
       Client: Docker Engine - Community
        Version:           24.0.4
        API version:       1.43
        Go version:        go1.20.5
        Git commit:        3713ee1
        Built:             Fri Jul  7 14:50:55 2023
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          24.0.4
         API version:      1.43 (minimum version 1.12)
         Go version:       go1.20.5
         Git commit:       4ffc614
         Built:            Fri Jul  7 14:50:55 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.21
         GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
        runc:
         Version:          1.1.7
         GitCommit:        v1.1.7-0-g860f061
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client: Docker Engine - Community
        Version:    24.0.4
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.11.1
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.19.1
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
       
       Server:
        Containers: 8
         Running: 5
         Paused: 0
         Stopped: 3
        Images: 19
        Server Version: 24.0.4
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
        runc version: v1.1.7-0-g860f061
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.19.0-50-generic
        Operating System: Ubuntu 22.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 8
        Total Memory: 31.13GiB
        Name: penguin-server
        ID: 900b75ce-7d2b-4b87-ba28-9cf332cb9a79
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 55
         Goroutines: 58
         System Time: 2023-08-02T12:54:09.178067684-04:00
         EventsListeners: 1
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: v0.6.0
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v254
         heroku-buildpack-nodejs    v213
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v232
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v234
         heroku-buildpack-go        v174
         heroku-buildpack-nginx     v23
         buildpack-null             v3
-----> dokku version: dokku version 0.30.9
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.30.9 enabled    dokku core standard plugin
         20_events            0.30.9 enabled    dokku core events logging plugin
         app-json             0.30.9 enabled    dokku core app-json plugin
         apps                 0.30.9 enabled    dokku core apps plugin
cat: /var/lib/dokku/plugins/available/build-env/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc0000100d0, 0x2, 0x5fadb9?})
	github.com/dokku/plugn/plugn.go:30 +0x1ab
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc000118280, {0xc0000100a0?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc000123e60, 0x4, 0xc00005c200?}, 0x495954?, 0x1, {0xc000018270, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x5fab59?, {0xc000123e60, 0x4, 0x4}, 0x5caa00?, 0x70?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x40c
cat: /var/lib/dokku/plugins/available/build-env/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc0000100d0, 0x2, 0x5fadb9?})
	github.com/dokku/plugn/plugn.go:30 +0x1ab
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc000098280, {0xc0000100a0?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc0000a3e60, 0x4, 0xc00005c200?}, 0x495954?, 0x1, {0xc000018270, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x5fab59?, {0xc0000a3e60, 0x4, 0x4}, 0x5caa00?, 0x70?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x40c
         build-env                  enabled    
         builder              0.30.9 enabled    dokku core builder plugin
         builder-dockerfile   0.30.9 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.9 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.9 enabled    dokku core builder-lambda plugin
         builder-null         0.30.9 enabled    dokku core builder-null plugin
         builder-pack         0.30.9 enabled    dokku core builder-pack plugin
         buildpacks           0.30.9 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.9 enabled    dokku core caddy-vhosts plugin
         certs                0.30.9 enabled    dokku core certificate management plugin
         cf-tunnel-update     0.1.0 enabled    dokku CloudFlare tunnel update (unofficial, no affiliation with Cloudflare)
         checks               0.30.9 enabled    dokku core checks plugin
         common               0.30.9 enabled    dokku core common plugin
         config               0.30.9 enabled    dokku core config plugin
         cron                 0.30.9 enabled    dokku core cron plugin
         docker-options       0.30.9 enabled    dokku core docker-options plugin
         domains              0.30.9 enabled    dokku core domains plugin
         enter                0.30.9 enabled    dokku core enter plugin
         git                  0.30.9 enabled    dokku core git plugin
         haproxy-vhosts       0.30.9 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.9 enabled    dokku core logs plugin
         network              0.30.9 enabled    dokku core network plugin
         nginx-vhosts         0.30.9 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.9 enabled    dokku core plugin plugin
         postgres             1.34.0 enabled    dokku postgres service plugin
         proxy                0.30.9 enabled    dokku core proxy plugin
         ps                   0.30.9 enabled    dokku core ps plugin
         registry             0.30.9 enabled    dokku core registry plugin
         repo                 0.30.9 enabled    dokku core repo plugin
         resource             0.30.9 enabled    dokku core resource plugin
         run                  0.30.9 enabled    dokku core run plugin
         scheduler            0.30.9 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.9 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.9 enabled    dokku core scheduler-null plugin
         shell                0.30.9 enabled    dokku core shell plugin
         ssh-keys             0.30.9 enabled    dokku core ssh-keys plugin
         storage              0.30.9 enabled    dokku core storage plugin
         trace                0.30.9 enabled    dokku core trace plugin
         traefik-vhosts       0.30.9 enabled    dokku core traefik-vhosts plugin
=====> djmuzach app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> djmuzach app information
       App created at:                1689992931
       App deploy source:             git-push
       App deploy source metadata:    1e612872a6c4da4448cc8f8939b11e97414ec506
       App dir:                       /home/dokku/djmuzach
       App locked:                    false
=====> djmuzach builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> djmuzach builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> djmuzach builder-herokuish information
       Builder herokuish computed allowed: true                     
       Builder herokuish global allowed: true                     
       Builder herokuish allowed:                              
=====> djmuzach builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> djmuzach builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> djmuzach buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> djmuzach caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.7
       Caddy letsencrypt email:                                
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR                    
       Caddy polling interval:        5s                       
       Caddy tls internal:            false                    
=====> djmuzach ssl information
       Ssl dir:                       /home/dokku/djmuzach/tls 
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> djmuzach checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
       Checks computed wait to retire: 60                       
       Checks global wait to retire:  60                       
       Checks wait to retire:                                  
=====> djmuzach cron information
       Cron task count:               0
=====> djmuzach docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> djmuzach domains information
       Domains app enabled:           true                     
       Domains app vhosts:            djmuzach.com             
       Domains global enabled:        true                     
       Domains global vhosts:         exa.zone                 
=====> djmuzach git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       1e61287                  
       Git source image:                                       
       Git last updated at:           1689992980               
=====> djmuzach haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0  
       Haproxy letsencrypt email:                              
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR                    
Could not open file or uri for loading certificate from /home/dokku/djmuzach/tls/server.crt
802B361DCB7F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
802B361DCB7F0000:error:80000002:system library:file_open:No such file or directory:../providers/implementations/storemgmt/file_store.c:267:calling stat(/home/dokku/djmuzach/tls/server.crt)
Unable to load certificate
=====> djmuzach letsencrypt information
       Letsencrypt active:            false                    
       Letsencrypt autorenew:         false                    
       Letsencrypt computed dns provider:                          
       Letsencrypt global dns provider:                          
       Letsencrypt dns provider:                               
       Letsencrypt computed email:    zachfeldman@gmail.com    
       Letsencrypt global email:                               
       Letsencrypt email:             zachfeldman@gmail.com    
       Letsencrypt expiration:        1690934400               
       Letsencrypt computed graceperiod: 2592000                  
       Letsencrypt global graceperiod:                          
       Letsencrypt graceperiod:                                
       Letsencrypt computed lego docker args:                          
       Letsencrypt global lego docker args:                          
       Letsencrypt lego docker args:                           
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:                              
       Letsencrypt server:                                     
=====> djmuzach logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> djmuzach network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.5:5000
=====> djmuzach nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/djmuzach-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/djmuzach-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx computed nginx conf sigil path: nginx.conf.sigil         
       Nginx global nginx conf sigil path: nginx.conf.sigil         
       Nginx nginx conf sigil path:                            
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1689992978               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> djmuzach proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx
=====> djmuzach ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: f24411e8de8)
=====> djmuzach registry information
       Registry computed image repo:      dokku/djmuzach
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> djmuzach resource information
=====> djmuzach scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> djmuzach scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> djmuzach storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     
=====> djmuzach traefik information
       Traefik api enabled:           false                    
       Traefik api vhost:             traefik.dokku.me         
       Traefik basic auth password:                            
       Traefik basic auth username:                            
       Traefik dashboard enabled:     false                    
       Traefik image:                 traefik:v2.8             
       Traefik letsencrypt email:                              
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR                    
       Traefik priority:           
```

### Additional information

Things I have tried:
- Setting the environment variables in .bashrc, sourcing this within the plugin's bash script
- Setting the environment variables "globally" with https://github.com/cameron-martin/dokku-build-env/tree/master
- Setting them per-app

They still don't seem to be echoed when the plugin calls them.

**Comment by josegonzalez** [comment]
I'm not sure why it doesn't work with you sourcing your .bashrc file but:

- that build-env plugin is deprecated and should not be used. It's functionality is built into Dokku and has been for years. You can tell its old because the `dokku report` output is blowing up since it doesn't have a `plugin.toml` file. Uninstall it.
- That `build-env` plugin was meant to make the environment variables available inside of the image that is being built, not the entire build process. It's not doing what you think it is.
- App config is not globally available within the build/deploy process for any app, you need to fetch it explicitly (see below).
- I recommend using the properties system inside of Dokku for managing plugin-specific properties. There isn't really any tutorial for it, but [here](https://github.com/dokku/dokku/blob/master/plugins/checks/subcommands/set) is an example `:set` subcommand. You'd [source](https://github.com/dokku/dokku/blob/master/plugins/checks/internal-functions#L3) the `property-functions` file and then [get](https://github.com/dokku/dokku/blob/master/plugins/checks/internal-functions#L88-L109) the property value you want later on.
- Other than the properties system, you can use the config plugin to fetch configuration. You'd need to [source the config functions file](https://github.com/dokku/dokku/blob/master/plugins/config/functions) and then use the correct function. I'd recommend against this because environment variables here are meant for use by the app, not by Dokku or it's plugins (the properties system is a better fit).

Hope that helps. Feel free to jump on our discord/slack (links in our docs) if you need further help.

**Comment by zachfeldman** [comment]
Thanks for looking at this so fast @josegonzalez ! We grabbed a drink back in NYC many years ago, not sure if you remember, but this project has grown so much since then - super cool.

The answer turned out to be a sort of footgun in `.bashrc` itself, described in this SO answer:
https://stackoverflow.com/questions/29948410/sourcing-bashrc-from-profile-not-working

Basically, `.bashrc` includes this line by default:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

So it exits out before getting to my env vars at the bottom, lol.

Appreciate the intel on the plugin, I uninstalled it! Things are working great now.

All the best!

**Comment by josegonzalez** [comment]
Generally if you want to have global settings, you either use an `/etc/default` file (we load `/etc/default/dokku` early on for all requests if its available) or `/etc/profile`.

Hope all is well!
