### ISSUE TITLE
Convert Procfile file line separator to LF if Windows CRLF when building from source

### ISSUE THREAD

**Issue by bradbajuz** [dokku/dokku#6490]
### Description of problem

If the Procfile file is set to CRLF and there is a newline after the `web:` line, for example, deployment will fail when building from source

Procfile example:
```
web: bundle exec puma -C config/puma.rb
worker: bundle exec good_job start
```

### Steps to reproduce

1. Convert Procfile to CRLF (if not already).
2. Add a worker line.
3. Deploy app.

### dokku report $APP_NAME

```
-----> uname: Linux ordersapp 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            1963         451         468          28        1044        1292
       Swap:              0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           24.0.7
        API version:       1.43
        Go version:        go1.20.10
        Git commit:        afdd53b
        Built:             Thu Oct 26 09:07:41 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          24.0.7
         API version:      1.43 (minimum version 1.12)
         Go version:       go1.20.10
         Git commit:       311b9ff
         Built:            Thu Oct 26 09:07:41 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.27
         GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
        runc:
         Version:          1.1.11
         GitCommit:        v1.1.11-0-g4bccb38
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    24.0.7
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.11.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.21.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 6
         Running: 3
         Paused: 0
         Stopped: 3
        Images: 12
        Server Version: 24.0.7
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
        runc version: v1.1.11-0-g4bccb38
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-91-generic
        Operating System: Ubuntu 22.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 1.918GiB
        Name: ordersapp
        ID: G4Y5:DCH2:JD3Z:2MZK:WTOU:HHD5:2DGE:6BTO:7PM7:SECS:QELF:ZRQ3
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 43
         Goroutines: 52
         System Time: 2024-01-19T22:30:35.703936909-05:00
         EventsListeners: 1
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
       herokuish: v0.7.2
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v259
         heroku-buildpack-nodejs    v224
         heroku-buildpack-clojure   v91
         heroku-buildpack-python    v237
         heroku-buildpack-java      v73
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v239
         heroku-buildpack-go        v181
         heroku-buildpack-nginx     v24
         buildpack-null             v3
-----> dokku version: dokku version 0.32.4
-----> dokku-event-listener version: 0.15.0build+5268732
-----> dokku-update version: dokku-update 0.7.2
-----> docker-container-healthchecker version: 0.7.2
-----> docker-image-labeler version: 0.6.1build+c6e15a9
-----> git version: git version 2.34.1
-----> lambda-builder version:        0.5.0
-----> netrc version: 0.7.1build+677c033
 !     pack binary is not available
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand 0.17.1
-----> dokku plugins:
         00_dokku-standard    0.32.4 enabled    dokku core standard plugin
         20_events            0.32.4 enabled    dokku core events logging plugin
         app-json             0.32.4 enabled    dokku core app-json plugin
         apps                 0.32.4 enabled    dokku core apps plugin
         builder              0.32.4 enabled    dokku core builder plugin
         builder-dockerfile   0.32.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.32.4 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.32.4 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.32.4 enabled    dokku core builder-nixpacks plugin
         builder-null         0.32.4 enabled    dokku core builder-null plugin
         builder-pack         0.32.4 enabled    dokku core builder-pack plugin
         buildpacks           0.32.4 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.32.4 enabled    dokku core caddy-vhosts plugin
         certs                0.32.4 enabled    dokku core certificate management plugin
         checks               0.32.4 enabled    dokku core checks plugin
         common               0.32.4 enabled    dokku core common plugin
         config               0.32.4 enabled    dokku core config plugin
         cron                 0.32.4 enabled    dokku core cron plugin
         docker-options       0.32.4 enabled    dokku core docker-options plugin
         domains              0.32.4 enabled    dokku core domains plugin
         enter                0.32.4 enabled    dokku core enter plugin
         git                  0.32.4 enabled    dokku core git plugin
         haproxy-vhosts       0.32.4 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.32.4 enabled    dokku core logs plugin
         network              0.32.4 enabled    dokku core network plugin
         nginx-vhosts         0.32.4 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.32.4 enabled    dokku core openresty-vhosts plugin
         plugin               0.32.4 enabled    dokku core plugin plugin
         ports                0.32.4 enabled    dokku core ports plugin
         postgres             1.36.1 enabled    dokku postgres service plugin
         proxy                0.32.4 enabled    dokku core proxy plugin
         ps                   0.32.4 enabled    dokku core ps plugin
         registry             0.32.4 enabled    dokku core registry plugin
         repo                 0.32.4 enabled    dokku core repo plugin
         resource             0.32.4 enabled    dokku core resource plugin
         run                  0.32.4 enabled    dokku core run plugin
         scheduler            0.32.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.32.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.32.4 enabled    dokku core scheduler-null plugin
         shell                0.32.4 enabled    dokku core shell plugin
         ssh-keys             0.32.4 enabled    dokku core ssh-keys plugin
         storage              0.32.4 enabled    dokku core storage plugin
         trace                0.32.4 enabled    dokku core trace plugin
         traefik-vhosts       0.32.4 enabled    dokku core traefik-vhosts plugin
=====> ordersapp app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> ordersapp app information
       App created at:                1671118500
       App deploy source:             git-push
       App deploy source metadata:    0ccd1d3e404dd91adac2086c36a173741d3921f1
       App dir:                       /home/dokku/ordersapp
       App locked:                    false
=====> ordersapp builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> ordersapp builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> ordersapp builder-herokuish information
       Builder herokuish computed allowed: true
       Builder herokuish global allowed: true
       Builder herokuish allowed:
=====> ordersapp builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> ordersapp builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml
       Builder nixpacks global nixpackstoml path: nixpacks.toml
       Builder nixpacks nixpackstoml path:
       Builder nixpacks computed no cache: false
       Builder nixpacks global no cache: false
       Builder nixpacks no cache:
=====> ordersapp builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> ordersapp buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> ordersapp caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.8
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> ordersapp ssl information
       Ssl dir:                       /home/dokku/ordersapp/tls
       Ssl enabled:                   true
       Ssl hostnames:                 ordersapp.xyz.xyz
       Ssl expires at:                Feb 19 04:00:07 2024 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Nov 21 04:00:08 2023 GMT
       Ssl subject:                   subject=CN = ordersapp.xyz.xyz
       Ssl verified:                  self signed
=====> ordersapp checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> ordersapp docker options information
       Docker options build:          --link dokku.postgres.db_ordersapp-16:dokku-postgres-db-ordersapp-16
       Docker options deploy:         --link dokku.postgres.db_ordersapp-16:dokku-postgres-db-ordersapp-16 --restart=on-failure:10 -v /var/li                                                                                                                                                 b/dokku/data/storage/ordersapp:/app/storage
       Docker options run:            --link dokku.postgres.db_ordersapp-16:dokku-postgres-db-ordersapp-16 -v /var/lib/dokku/data/storage/ord                                                                                                                                                 ersapp:/app/storage
=====> ordersapp domains information
       Domains app enabled:           true
       Domains app vhosts:            ordersapp.xyz.xyz
       Domains global enabled:        true
       Domains global vhosts:         xyz.xyz
=====> ordersapp git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       0ccd1d3
       Git source image:
       Git last updated at:           1705720131
=====> ordersapp haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> ordersapp letsencrypt information
       Letsencrypt active:            true
       Letsencrypt autorenew:         true
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    brad@xyz.xyz
       Letsencrypt global email:
       Letsencrypt email:             brad@xyz.xyz
       Letsencrypt expiration:        1708315207
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> ordersapp logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> ordersapp network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.5:5000
=====> ordersapp nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/ordersapp-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/ordersapp-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1705721394
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> ordersapp openresty information
       Openresty access log format:
       Openresty access log path:     /var/log/nginx/ordersapp-access.log
       Openresty bind address ipv4:
       Openresty bind address ipv6:   ::
       Openresty client max body size:
       Openresty error log path:      /var/log/nginx/ordersapp-error.log
       Openresty global hsts:         true
       Openresty computed hsts:       true
       Openresty hsts:
       Openresty hsts include subdomains: true
       Openresty hsts max age:        15724800
       Openresty hsts preload:        false
       Openresty image:               dokku/openresty-docker-proxy:0.6.0
       Openresty letsencrypt email:
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4096
       Openresty proxy buffering:     on
       Openresty proxy buffers:       8 4096
       Openresty proxy busy buffers size: 8192
       Openresty proxy read timeout:  60s
       Openresty x forwarded for value: $remote_addr
       Openresty x forwarded port value: $server_port
       Openresty x forwarded proto value: $scheme
       Openresty x forwarded ssl:
=====> ordersapp ports information
       Ports map:                     http:80:5000 https:443:5000
       Ports map detected:            http:80:5000 https:443:5000
=====> ordersapp proxy information
       Proxy enabled:                 true
       Proxy type:                    nginx
=====> ordersapp ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 126844405f2)
=====> ordersapp registry information
       Registry computed image repo:      dokku/ordersapp
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> ordersapp resource information
=====> ordersapp scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> ordersapp scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> ordersapp storage information
       Storage build mounts:
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/ordersapp:/app/storage
       Storage run mounts:            -v /var/lib/dokku/data/storage/ordersapp:/app/storage
=====> ordersapp traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:v2.10
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik priority:

```

### Additional information

Error when deploying:
```
remote:  !     Failure in name='port listening check': container state is not running
9ce809c75076aedd2ba479c448af21dbc28d9cdfcdbd461d020dd01ac5e12eec
remote:  !     Could not start due to 1 failed checks (web.1)
=====> Start of ordersapp container output (web.1)
       bundler: failed to load command: puma (/app/vendor/bundle/ruby/3.3.0/bin/puma)
remote:  (Errno::ENOENT)
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/dsl.rb:133:in `_load_from'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:239:in `block in load'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:239:in `each'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:239:in `load'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/launcher.rb:54:in `initialize'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cli.rb:66:in `new'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cli.rb:66:in `initialize'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/bin/puma:8:in `new'
        from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/bin/puma:8:in `<top (required)>'
        from /app/vendor/bundle/ruby/3.3.0/bin/puma:25:in `load'
        from /app/vendor/bundle/ruby/3.3.0/bin/puma:25:in `<top (required)>'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
        from /app/vendor/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
        from /app/vendor/ruby-3.3.0/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /app/vendor/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
        from /app/bin/bundle:3:in `load'
        from /app/bin/bundle:3:in `<main>'
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
